// etf_data.js
// ETF News — weekly data file.
// Replaced every Thursday during the live pipeline run. index.html reads this
// and never needs to change. Generated by update_etf_data.py from justETF
// data (EUR); whyItMoved researched fields are filled in by Claude afterwards.

const LEDGER_DATA = {
  "meta": {
    "asOf": "21 Aug 2026, close",
    "fundsTracked": 272,
    "matchedFunds": 258
  },
  "performers": {
    "1m": {
      "best": [
        {
          "tier": "researched",
          "ticker": "AUCO",
          "name": "L&G Gold Mining",
          "category": "Gold mining",
          "pct": 40.79,
          "holds": "L&G Gold Mining — Gold mining fund on the Lightyear list. ~45 holdings.",
          "vsCategory": "Outperformed the Gold mining category average (+40.8%) by ~0pts over 1M.",
          "returnRisk": "1.9 return/risk (1Y, EUR); 1Y volatility 43%.",
          "week52": "83% of 52-week range.",
          "aumFlow": "AUM EUR 799M — flow baseline being established (first tracked period).",
          "aumEurM": 799,
          "whyItMoved": "Gold rallied ~10% in August from near $4,000 to $4,558 after cooler-than-expected CPI data damped Fed rate-hike expectations. Gold miners amplified the underlying metal move with high-beta exposure; continued central-bank buying (particularly China) and Middle East geopolitical risk premiums added further support.",
          "topHoldings": "Newmont Corp. ~16%, Agnico Eagle Mines Ltd. ~11%, Anglogold Ashanti Plc ~10%, Gold Fields Ltd. ~7%, Kinross Gold Corp. ~6% — top 10 = ~68%."
        },
        {
          "tier": "researched",
          "ticker": "IAUP",
          "name": "iShares Gold Producers",
          "category": "Gold mining stocks",
          "pct": 36.07,
          "holds": "iShares Gold Producers — Gold mining stocks fund on the Lightyear list. ~82 holdings.",
          "vsCategory": "Outperformed the Gold mining stocks category average (+36.1%) by ~0pts over 1M.",
          "returnRisk": "1.8 return/risk (1Y, EUR); 1Y volatility 41%.",
          "week52": "80% of 52-week range.",
          "aumFlow": "AUM EUR 3,987M (+37.8% 1M). Implied flow +1.7pp vs return — net inflows beyond price effect.",
          "aumEurM": 3987,
          "whyItMoved": "Same gold surge to $4,558 on soft CPI and fading rate-hike odds lifted the entire gold-miner complex. Broader fund with ~82 holdings captured the move across large-cap miners like Agnico Eagle, Newmont, and Barrick; strong AUM inflows (+1.7pp above return) confirm investor demand for gold exposure.",
          "topHoldings": "Agnico Eagle Mines Ltd. ~10%, Newmont Corp. ~10%, Barrick Mining Corp. ~9%, Wheaton Precious Metals Corp. ~7%, Franco-Nevada ~6% — top 10 = ~61%."
        },
        {
          "tier": "screener",
          "ticker": "CEBT",
          "name": "iShares Essential Metals Producers",
          "category": "Essential metals producers stocks",
          "pct": 17.43,
          "holds": "iShares Essential Metals Producers — Essential metals producers stocks fund on the Lightyear list. ~81 holdings.",
          "vsCategory": "Outperformed the Essential metals producers stocks category average (+17.4%) by ~0pts over 1M.",
          "returnRisk": "2.6 return/risk (1Y, EUR); 1Y volatility 33%.",
          "week52": "89% of 52-week range.",
          "aumFlow": "AUM EUR 864M — flow baseline being established (first tracked period).",
          "aumEurM": 864
        },
        {
          "tier": "screener",
          "ticker": "CEBS",
          "name": "iShares Copper Miners",
          "category": "Copper mining stocks",
          "pct": 16.87,
          "holds": "iShares Copper Miners — Copper mining stocks fund on the Lightyear list. ~44 holdings.",
          "vsCategory": "Outperformed the Copper mining stocks category average (+16.9%) by ~0pts over 1M.",
          "returnRisk": "3.0 return/risk (1Y, EUR); 1Y volatility 33%.",
          "week52": "100% of 52-week range.",
          "aumFlow": "AUM EUR 490M — flow baseline being established (first tracked period).",
          "aumEurM": 490
        },
        {
          "tier": "screener",
          "ticker": "WREE",
          "name": "WisdomTree Energy Transition Metals and Rare Earths Miners",
          "category": "Metals and Earths Miners",
          "pct": 14.4,
          "holds": "WisdomTree Energy Transition Metals and Rare Earths Miners — Metals and Earths Miners fund on the Lightyear list. ~81 holdings.",
          "vsCategory": "Outperformed the Metals and Earths Miners category average (+14.4%) by ~0pts over 1M.",
          "returnRisk": "1.9 return/risk (1Y, EUR); 1Y volatility 32%.",
          "week52": "68% of 52-week range.",
          "aumFlow": "AUM EUR 793M — flow baseline being established (first tracked period).",
          "aumEurM": 793
        }
      ],
      "worst": [
        {
          "tier": "researched",
          "ticker": "SMGB",
          "name": "VanEck Semiconductor",
          "category": "Semiconductors / US semiconductor stocks",
          "pct": -7.54,
          "holds": "VanEck Semiconductor — Semiconductors / US semiconductor stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Semiconductors / US semiconductor stocks category average (-7.5%) by ~0pts over 1M.",
          "returnRisk": "2.9 return/risk (1Y, EUR); 1Y volatility 41%.",
          "week52": "70% of 52-week range.",
          "aumFlow": "AUM EUR 7,378M (+12.1% 1M). Implied flow +19.7pp vs return — net inflows beyond price effect.",
          "aumEurM": 7378,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "Semiconductor sell-off deepened in August after Broadcom issued a cautious AI-chip outlook and global smartphone demand hit a decade low (volumes forecast down 13% YoY). Rising Treasury yields pressured high-multiple chip names; the Philadelphia Semiconductor Index fell ~10% in the month, roughly double the Nasdaq 100's loss.",
          "topHoldings": "Micron Technology ~11%, AMD ~11%, Taiwan Semiconductor Manufacturing Co., Ltd. ~10%, ASML Holding NV ~10%, Broadcom Inc. ~9% — top 10 = ~83%."
        },
        {
          "tier": "researched",
          "ticker": "SEC0",
          "name": "iShares MSCI Global Semiconductors",
          "category": "Global semiconductor stocks",
          "pct": -7.0,
          "holds": "iShares MSCI Global Semiconductors — Global semiconductor stocks fund on the Lightyear list. ~260 holdings.",
          "vsCategory": "Outperformed the Global semiconductor stocks category average (-7.0%) by ~0pts over 1M.",
          "returnRisk": "3.7 return/risk (1Y, EUR); 1Y volatility 37%.",
          "week52": "68% of 52-week range.",
          "aumFlow": "AUM EUR 4,986M (+15.4% 1M). Implied flow +22.4pp vs return — net inflows beyond price effect.",
          "aumEurM": 4986,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "Caught in the same August chip sell-off: Broadcom's cautious AI-chip guidance, collapsing smartphone volumes, and rising yields hit the sector. Broader 260-holding fund fell slightly less than the concentrated VanEck peer, but still tracked the Philadelphia Semiconductor Index's ~10% monthly decline.",
          "topHoldings": "Micron Technology ~10%, AMD ~8%, Taiwan Semiconductor Manufacturing Co., Ltd. ~6%, Applied Materials, Inc. ~6%, Lam Research ~5% — top 10 = ~60%."
        },
        {
          "tier": "screener",
          "ticker": "IEMB",
          "name": "iShares J.P. Morgan USD Emerging Markets Bond",
          "category": "Emerging markets government bonds",
          "pct": -2.94,
          "holds": "iShares J.P. Morgan USD Emerging Markets Bond — Emerging markets government bonds fund on the Lightyear list. ~620 holdings.",
          "vsCategory": "Underperformed the Emerging markets government bonds category average (-2.0%) by ~1pts over 1M.",
          "returnRisk": "1.1 return/risk (1Y, EUR); 1Y volatility 5%.",
          "week52": "54% of 52-week range.",
          "aumFlow": "AUM EUR 3,768M — flow baseline being established (first tracked period).",
          "aumEurM": 3768
        },
        {
          "tier": "screener",
          "ticker": "LQDA",
          "name": "iShares USD Corporate Bond",
          "category": "USD corporate bonds",
          "pct": -2.75,
          "holds": "iShares USD Corporate Bond — USD corporate bonds fund on the Lightyear list. ~3111 holdings.",
          "vsCategory": "Outperformed the USD corporate bonds category average (-2.8%) by ~0pts over 1M.",
          "returnRisk": "0.1 return/risk (1Y, EUR); 1Y volatility 8%.",
          "week52": "19% of 52-week range.",
          "aumFlow": "AUM EUR 3,990M — flow baseline being established (first tracked period).",
          "aumEurM": 3990
        },
        {
          "tier": "screener",
          "ticker": "EXXT",
          "name": "iShares NASDAQ 100",
          "category": "US technology stocks",
          "pct": -1.76,
          "holds": "iShares NASDAQ 100 — US technology stocks fund on the Lightyear list. ~102 holdings.",
          "vsCategory": "Underperformed the US technology stocks category average (-1.4%) by ~0pts over 1M.",
          "returnRisk": "1.4 return/risk (1Y, EUR); 1Y volatility 19%.",
          "week52": "78% of 52-week range.",
          "aumFlow": "AUM EUR 5,335M — flow baseline being established (first tracked period).",
          "aumEurM": 5335
        }
      ]
    },
    "6m": {
      "best": [
        {
          "tier": "researched",
          "ticker": "CYSE",
          "name": "WisdomTree Cybersecurity",
          "category": "Cybersecurity stocks",
          "pct": 58.78,
          "holds": "WisdomTree Cybersecurity — Cybersecurity stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Cybersecurity stocks category average (+58.8%) by ~0pts over 6M.",
          "returnRisk": "0.9 return/risk (1Y, EUR); 1Y volatility 35%.",
          "week52": "76% of 52-week range.",
          "aumFlow": "AUM EUR 431M (+20.7% 1M). Implied flow +19.1pp vs return — net inflows beyond price effect.",
          "aumEurM": 431,
          "whyItMoved": "AI-driven security demand powered the cybersecurity sector: CrowdStrike and Palo Alto Networks hit record highs after the Black Hat conference highlighted surging enterprise spend on AI security tools. UBS models the global cyber market growing ~13% to $240B in 2026; analyst upgrades in July accelerated momentum across the concentrated 25-holding fund.",
          "topHoldings": "CrowdStrike Holdings ~8%, Palo Alto Networks ~7%, Datadog ~7%, Fortinet Inc ~6%, Okta ~6% — top 10 = ~59%."
        },
        {
          "tier": "researched",
          "ticker": "SEC0",
          "name": "iShares MSCI Global Semiconductors",
          "category": "Global semiconductor stocks",
          "pct": 45.4,
          "holds": "iShares MSCI Global Semiconductors — Global semiconductor stocks fund on the Lightyear list. ~260 holdings.",
          "vsCategory": "Outperformed the Global semiconductor stocks category average (+45.4%) by ~0pts over 6M.",
          "returnRisk": "3.7 return/risk (1Y, EUR); 1Y volatility 37%.",
          "week52": "68% of 52-week range.",
          "aumFlow": "AUM EUR 4,986M (+15.4% 1M). Implied flow +22.4pp vs return — net inflows beyond price effect.",
          "aumEurM": 4986,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "AI data-center capex surge drove the six-month gain: Magnificent Seven projected to spend $527B on AI infrastructure in 2026, boosting Micron, AMD, Applied Materials, and Lam Research. Memory supercycle (HBM demand for NVIDIA/AMD accelerators) and strong Q1 NAND revenue growth (+84% QoQ) underpinned the rally before August's sell-off trimmed gains.",
          "topHoldings": "Micron Technology ~10%, AMD ~8%, Taiwan Semiconductor Manufacturing Co., Ltd. ~6%, Applied Materials, Inc. ~6%, Lam Research ~5% — top 10 = ~60%."
        },
        {
          "tier": "screener",
          "ticker": "SMGB",
          "name": "VanEck Semiconductor",
          "category": "Semiconductors / US semiconductor stocks",
          "pct": 44.82,
          "holds": "VanEck Semiconductor — Semiconductors / US semiconductor stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Semiconductors / US semiconductor stocks category average (+44.8%) by ~0pts over 6M.",
          "returnRisk": "2.9 return/risk (1Y, EUR); 1Y volatility 41%.",
          "week52": "70% of 52-week range.",
          "aumFlow": "AUM EUR 7,378M (+12.1% 1M). Implied flow +19.7pp vs return — net inflows beyond price effect.",
          "aumEurM": 7378,
          "badges": [
            "reversal watch"
          ]
        },
        {
          "tier": "screener",
          "ticker": "AIFS",
          "name": "iShares AI Infrastructure",
          "category": "AI infrastructure stocks",
          "pct": 43.8,
          "holds": "iShares AI Infrastructure — AI infrastructure stocks fund on the Lightyear list. ~52 holdings.",
          "vsCategory": "Outperformed the AI infrastructure stocks category average (+43.8%) by ~0pts over 6M.",
          "returnRisk": "3.3 return/risk (1Y, EUR); 1Y volatility 26%.",
          "week52": "84% of 52-week range.",
          "aumFlow": "AUM EUR 1,057M (+23.8% 1M). Implied flow +23.7pp vs return — net inflows beyond price effect.",
          "aumEurM": 1057
        },
        {
          "tier": "screener",
          "ticker": "ITWN",
          "name": "iShares MSCI Taiwan",
          "category": "Taiwan large and mid-cap stocks",
          "pct": 43.19,
          "holds": "iShares MSCI Taiwan — Taiwan large and mid-cap stocks fund on the Lightyear list. ~78 holdings.",
          "vsCategory": "Outperformed the Taiwan large and mid-cap stocks category average (+43.2%) by ~0pts over 6M.",
          "returnRisk": "3.0 return/risk (1Y, EUR); 1Y volatility 30%.",
          "week52": "84% of 52-week range.",
          "aumFlow": "AUM EUR 1,336M (+12.6% 1M). Implied flow +10.7pp vs return — net inflows beyond price effect.",
          "aumEurM": 1336
        }
      ],
      "worst": [
        {
          "tier": "researched",
          "ticker": "DFEN",
          "name": "VanEck Defense",
          "category": "Defence stocks / Defense stocks",
          "pct": -7.98,
          "holds": "VanEck Defense — Defence stocks / Defense stocks fund on the Lightyear list. ~45 holdings.",
          "vsCategory": "Outperformed the Defence stocks / Defense stocks category average (-8.0%) by ~0pts over 6M.",
          "returnRisk": "0.5 return/risk (1Y, EUR); 1Y volatility 25%.",
          "week52": "41% of 52-week range.",
          "aumFlow": "AUM EUR 6,845M (+12.2% 1M). Implied flow +3.3pp vs return — net inflows beyond price effect.",
          "aumEurM": 6845,
          "whyItMoved": "Defense sector consolidated after a strong 2025 surge. Ceasefire announcements (Iran-Israel memorandum of understanding), profit-taking at elevated valuations, and investor rotation into AI/tech themes weighed on the space. The Stoxx Europe Aerospace & Defence index turned negative YTD as investors became more selective, though Palantir's ~8% fund weight provided partial offset.",
          "topHoldings": "RTX ~9%, Palantir Technologies, Inc. ~8%, Thales SA ~7%, Curtiss-Wright ~6%, Leonardo SpA ~6% — top 10 = ~58%."
        },
        {
          "tier": "researched",
          "ticker": "IIND",
          "name": "iShares MSCI India",
          "category": "Indian stocks",
          "pct": -5.82,
          "holds": "iShares MSCI India — Indian stocks fund on the Lightyear list. ~166 holdings.",
          "vsCategory": "Outperformed the Indian stocks category average (-5.8%) by ~0pts over 6M.",
          "returnRisk": "-0.6 return/risk (1Y, EUR); 1Y volatility 16%.",
          "week52": "37% of 52-week range.",
          "aumFlow": "AUM EUR 4,447M (-2.0% 1M). Flow roughly neutral — AUM change tracks the price move.",
          "aumEurM": 4447,
          "whyItMoved": "Middle East conflict drove oil prices higher, hitting India hard as a major crude importer and stoking inflation concerns. Foreign portfolio investors withdrew roughly $30B from Indian equities (concentrated in financials and IT), amplifying downside pressure on index heavyweights like HDFC Bank and Infosys.",
          "topHoldings": "HDFC Bank Ltd. ~7%, Reliance Industries Ltd. ~6%, ICICI Bank Ltd. ~6%, Bharti Airtel Ltd. ~4%, Infosys Ltd. ~2% — top 10 = ~35%."
        },
        {
          "tier": "screener",
          "ticker": "EUDF",
          "name": "WisdomTree Europe Defence",
          "category": "European defence stocks / European defense stocks",
          "pct": -5.23,
          "holds": "WisdomTree Europe Defence — European defence stocks / European defense stocks fund on the Lightyear list. ~38 holdings.",
          "vsCategory": "Outperformed the European defence stocks / European defense stocks category average (-5.2%) by ~0pts over 6M.",
          "returnRisk": "0.5 return/risk (1Y, EUR); 1Y volatility 27%.",
          "week52": "74% of 52-week range.",
          "aumFlow": "AUM EUR 4,732M (+4.4% 1M). Implied flow -6.0pp vs return — money is leaving despite the price move.",
          "aumEurM": 4732
        },
        {
          "tier": "screener",
          "ticker": "SEGA",
          "name": "iShares Core Euro Government Bond",
          "category": "Eurozone government bonds",
          "pct": -2.39,
          "holds": "iShares Core Euro Government Bond — Eurozone government bonds fund on the Lightyear list. ~551 holdings.",
          "vsCategory": "Outperformed the Eurozone government bonds category average (-2.4%) by ~0pts over 6M.",
          "returnRisk": "-0.0 return/risk (1Y, EUR); 1Y volatility 4%.",
          "week52": "16% of 52-week range.",
          "aumFlow": "AUM EUR 5,389M (+0.7% 1M). Implied flow +1.0pp vs return — net inflows beyond price effect.",
          "aumEurM": 5389
        },
        {
          "tier": "screener",
          "ticker": "LQDA",
          "name": "iShares USD Corporate Bond",
          "category": "USD corporate bonds",
          "pct": -2.21,
          "holds": "iShares USD Corporate Bond — USD corporate bonds fund on the Lightyear list. ~3111 holdings.",
          "vsCategory": "Outperformed the USD corporate bonds category average (-2.2%) by ~0pts over 6M.",
          "returnRisk": "0.1 return/risk (1Y, EUR); 1Y volatility 8%.",
          "week52": "19% of 52-week range.",
          "aumFlow": "AUM EUR 3,990M — flow baseline being established (first tracked period).",
          "aumEurM": 3990
        }
      ]
    },
    "ytd": {
      "best": [
        {
          "tier": "researched",
          "ticker": "IKOR",
          "name": "iShares MSCI Korea",
          "category": "Korean stocks",
          "pct": 84.27,
          "holds": "iShares MSCI Korea — Korean stocks fund on the Lightyear list. ~77 holdings.",
          "vsCategory": "Outperformed the Korean stocks category average (+84.3%) by ~0pts over YTD.",
          "returnRisk": "2.8 return/risk (1Y, EUR); 1Y volatility 57%.",
          "week52": "74% of 52-week range.",
          "aumFlow": "AUM EUR 977M (+18.1% 1M). Implied flow +13.0pp vs return — net inflows beyond price effect.",
          "aumEurM": 977,
          "whyItMoved": "HBM memory supercycle powered KOSPI up 47%+ in 2026: Samsung (~29% of fund) and SK Hynix (~18%) produce the bulk of high-bandwidth memory essential for AI accelerators. Corporate governance reforms attracted massive foreign inflows, and Q1 NAND revenue surged 84% QoQ across top-five suppliers.",
          "topHoldings": "Samsung Electronics Co., Ltd. ~29%, SK hynix, Inc. ~18%, SK Square Co. Ltd. ~6%, Samsung Electro-Mechanics Co., Ltd. ~4%, Samsung Electronics Co., Ltd. ~3% — top 10 = ~69%."
        },
        {
          "tier": "researched",
          "ticker": "SEC0",
          "name": "iShares MSCI Global Semiconductors",
          "category": "Global semiconductor stocks",
          "pct": 77.06,
          "holds": "iShares MSCI Global Semiconductors — Global semiconductor stocks fund on the Lightyear list. ~260 holdings.",
          "vsCategory": "Outperformed the Global semiconductor stocks category average (+77.1%) by ~0pts over YTD.",
          "returnRisk": "3.7 return/risk (1Y, EUR); 1Y volatility 37%.",
          "week52": "68% of 52-week range.",
          "aumFlow": "AUM EUR 4,986M (+15.4% 1M). Implied flow +22.4pp vs return — net inflows beyond price effect.",
          "aumEurM": 4986,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "Full-year AI investment momentum drove YTD gains: hyperscaler capex projected at $527B, HBM demand from NVIDIA/AMD accelerators lifted Micron and Applied Materials, and the SMH semiconductor ETF returned 50%+ YTD. August's sell-off on cautious Broadcom guidance and smartphone weakness trimmed but didn't erase the strong H1 rally.",
          "topHoldings": "Micron Technology ~10%, AMD ~8%, Taiwan Semiconductor Manufacturing Co., Ltd. ~6%, Applied Materials, Inc. ~6%, Lam Research ~5% — top 10 = ~60%."
        },
        {
          "tier": "screener",
          "ticker": "SMGB",
          "name": "VanEck Semiconductor",
          "category": "Semiconductors / US semiconductor stocks",
          "pct": 70.98,
          "holds": "VanEck Semiconductor — Semiconductors / US semiconductor stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Semiconductors / US semiconductor stocks category average (+71.0%) by ~0pts over YTD.",
          "returnRisk": "2.9 return/risk (1Y, EUR); 1Y volatility 41%.",
          "week52": "70% of 52-week range.",
          "aumFlow": "AUM EUR 7,378M (+12.1% 1M). Implied flow +19.7pp vs return — net inflows beyond price effect.",
          "aumEurM": 7378,
          "badges": [
            "reversal watch"
          ]
        },
        {
          "tier": "screener",
          "ticker": "ITWN",
          "name": "iShares MSCI Taiwan",
          "category": "Taiwan large and mid-cap stocks",
          "pct": 64.35,
          "holds": "iShares MSCI Taiwan — Taiwan large and mid-cap stocks fund on the Lightyear list. ~78 holdings.",
          "vsCategory": "Outperformed the Taiwan large and mid-cap stocks category average (+64.3%) by ~0pts over YTD.",
          "returnRisk": "3.0 return/risk (1Y, EUR); 1Y volatility 30%.",
          "week52": "84% of 52-week range.",
          "aumFlow": "AUM EUR 1,336M (+12.6% 1M). Implied flow +10.7pp vs return — net inflows beyond price effect.",
          "aumEurM": 1336
        },
        {
          "tier": "screener",
          "ticker": "LSMC",
          "name": "Amundi MSCI Semiconductors",
          "category": "Semiconductor industry stocks",
          "pct": 52.59,
          "holds": "Amundi MSCI Semiconductors — Semiconductor industry stocks fund on the Lightyear list. ~71 holdings.",
          "vsCategory": "Outperformed the Semiconductor industry stocks category average (+52.6%) by ~0pts over YTD.",
          "returnRisk": "2.8 return/risk (1Y, EUR); 1Y volatility 32%.",
          "week52": "74% of 52-week range.",
          "aumFlow": "AUM EUR 1,816M (+12.4% 1M). Implied flow +16.8pp vs return — net inflows beyond price effect.",
          "aumEurM": 1816
        }
      ],
      "worst": [
        {
          "tier": "researched",
          "ticker": "IIND",
          "name": "iShares MSCI India",
          "category": "Indian stocks",
          "pct": -8.76,
          "holds": "iShares MSCI India — Indian stocks fund on the Lightyear list. ~166 holdings.",
          "vsCategory": "Outperformed the Indian stocks category average (-8.8%) by ~0pts over YTD.",
          "returnRisk": "-0.6 return/risk (1Y, EUR); 1Y volatility 16%.",
          "week52": "37% of 52-week range.",
          "aumFlow": "AUM EUR 4,447M (-2.0% 1M). Flow roughly neutral — AUM change tracks the price move.",
          "aumEurM": 4447,
          "whyItMoved": "MSCI India fell 18% in Q1 as Middle East conflict drove oil prices sharply higher, hitting India as a major net importer. FPI withdrawals of ~$30B (concentrated in financials and IT) amplified selling. A 10% Q2 recovery partially offset Q1 losses, but the index remains underwater YTD while broader EM markets rallied on AI/chip tailwinds.",
          "topHoldings": "HDFC Bank Ltd. ~7%, Reliance Industries Ltd. ~6%, ICICI Bank Ltd. ~6%, Bharti Airtel Ltd. ~4%, Infosys Ltd. ~2% — top 10 = ~35%."
        },
        {
          "tier": "researched",
          "ticker": "LQDA",
          "name": "iShares USD Corporate Bond",
          "category": "USD corporate bonds",
          "pct": -0.93,
          "holds": "iShares USD Corporate Bond — USD corporate bonds fund on the Lightyear list. ~3111 holdings.",
          "vsCategory": "Outperformed the USD corporate bonds category average (-0.9%) by ~0pts over YTD.",
          "returnRisk": "0.1 return/risk (1Y, EUR); 1Y volatility 8%.",
          "week52": "19% of 52-week range.",
          "aumFlow": "AUM EUR 3,990M — flow baseline being established (first tracked period).",
          "aumEurM": 3990,
          "whyItMoved": "Rising Treasury yields weighed on USD corporate bonds throughout 2026 — driven by elevated deficit spending, persistent above-target inflation, surging AI-related corporate debt issuance competing for investor favor, and increasing term premia on long-dated US debt. The 30-year yield approached multi-decade highs, pressuring existing bond prices.",
          "topHoldings": "INSL CASH ~1% — top 1 = ~1%."
        },
        {
          "tier": "screener",
          "ticker": "SEGA",
          "name": "iShares Core Euro Government Bond",
          "category": "Eurozone government bonds",
          "pct": -0.84,
          "holds": "iShares Core Euro Government Bond — Eurozone government bonds fund on the Lightyear list. ~551 holdings.",
          "vsCategory": "Outperformed the Eurozone government bonds category average (-0.9%) by ~0pts over YTD.",
          "returnRisk": "-0.0 return/risk (1Y, EUR); 1Y volatility 4%.",
          "week52": "16% of 52-week range.",
          "aumFlow": "AUM EUR 5,389M (+0.7% 1M). Implied flow +1.0pp vs return — net inflows beyond price effect.",
          "aumEurM": 5389
        },
        {
          "tier": "screener",
          "ticker": "VECP",
          "name": "Vanguard EUR Corporate Bond",
          "category": "Eurozone corporate bonds",
          "pct": 0.01,
          "holds": "Vanguard EUR Corporate Bond — Eurozone corporate bonds fund on the Lightyear list. ~3565 holdings.",
          "vsCategory": "Underperformed the Eurozone corporate bonds category average (+0.2%) by ~0pts over YTD.",
          "returnRisk": "0.3 return/risk (1Y, EUR); 1Y volatility 3%.",
          "week52": "52% of 52-week range.",
          "aumFlow": "AUM EUR 3,293M (+1.0% 1M). Implied flow +1.3pp vs return — net inflows beyond price effect.",
          "aumEurM": 3293
        },
        {
          "tier": "screener",
          "ticker": "IEAC",
          "name": "iShares Core Euro Corporate Bond",
          "category": "Eurozone corporate bonds",
          "pct": 0.34,
          "holds": "iShares Core Euro Corporate Bond — Eurozone corporate bonds fund on the Lightyear list. ~4144 holdings.",
          "vsCategory": "Outperformed the Eurozone corporate bonds category average (+0.2%) by ~0pts over YTD.",
          "returnRisk": "0.4 return/risk (1Y, EUR); 1Y volatility 3%.",
          "week52": "64% of 52-week range.",
          "aumFlow": "AUM EUR 8,695M — flow baseline being established (first tracked period).",
          "aumEurM": 8695
        }
      ]
    }
  },
  "portfolio": [
    {
      "ticker": "SEC0",
      "name": "iShares MSCI Global Semiconductors UCITS ETF USD (Acc)",
      "pct1m": -7.0,
      "pct6m": 45.4,
      "pctYtd": 77.06,
      "aumEurM": 4986,
      "holds": "The iShares MSCI Global Semiconductors UCITS ETF USD (Acc) seeks to track the MSCI ACWI IMI Semiconductors & Semiconductor Equipment ESG Screened Select Capped index. The MSCI ACWI IMI Semiconductors & Semiconductor Equipment ESG Screened Select Capped index tracks large, mid and small cap companies across 23 Developed Markets and 24 Emerging Markets that are active in the semiconductor industry. The stocks included are filtered according to ESG criteria (environmental, social and corporate governance).",
      "whyItMoved": "August chip sell-off (Broadcom's cautious AI guidance, smartphone demand at a decade low) drove the 1M loss. YTD +77% and 6M +45% reflect the AI capex supercycle: hyperscalers projected to spend $527B on AI infrastructure, HBM demand boosting Micron and AMD, and SMH returning 50%+ YTD.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "68% of 52-week range.",
      "aumFlow": "AUM EUR 4,986M (+15.4% 1M). Implied flow +22.4pp vs return — net inflows beyond price effect.",
      "topHoldings": "Micron Technology ~10%, AMD ~8%, Taiwan Semiconductor Manufacturing Co., Ltd. ~6%, Applied Materials, Inc. ~6%, Lam Research ~5% — top 10 = ~60%."
    },
    {
      "ticker": "AIFS",
      "name": "iShares AI Infrastructure UCITS ETF USD (Acc)",
      "pct1m": 0.11,
      "pct6m": 43.8,
      "pctYtd": 51.7,
      "aumEurM": 1057,
      "holds": "The iShares AI Infrastructure UCITS ETF USD (Acc) seeks to track the STOXX Global AI Infrastructure index. The STOXX Global AI Infrastructure index tracks the performance of companies worldwide that are engaged in the field of AI infrastructure. The stocks included are filtered according to ESG criteria (environmental, social and corporate governance).",
      "whyItMoved": "Near-flat 1M as the broader chip sell-off offset continued AI infrastructure investment. The 6M +44% and YTD +52% reflect Magnificent Seven deploying $527B in AI/data-center capex, boosting holdings like Applied Materials, KLA, and AMD. Strong AUM inflows (+23.7pp above return) signal conviction in the AI buildout thesis.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "84% of 52-week range.",
      "aumFlow": "AUM EUR 1,057M (+23.8% 1M). Implied flow +23.7pp vs return — net inflows beyond price effect.",
      "topHoldings": "Applied Materials, Inc. ~5%, KLA Corp. ~5%, Intel Corp. ~4%, AMD ~4%, Palo Alto Networks ~4% — top 10 = ~43%."
    },
    {
      "ticker": "XAIX",
      "name": "Xtrackers Artificial Intelligence & Big Data UCITS ETF 1C",
      "pct1m": 1.88,
      "pct6m": 32.85,
      "pctYtd": 30.84,
      "aumEurM": 7685,
      "holds": "The Xtrackers Artificial Intelligence & Big Data UCITS ETF 1C seeks to track the Nasdaq Global Artificial Intelligence and Big Data index. The Nasdaq Global Artificial Intelligence and Big Data index tracks international companies of the sectors artificial intelligence, big data and cyber security. The stocks included are filtered according to ESG criteria (environmental, social and corporate governance).",
      "whyItMoved": "Diversified AI/big data/cybersecurity exposure held up better than pure-play semis in August (+1.9% vs sector's -7%). Heavy Samsung/SK Hynix/Micron/Intel weighting captured the memory supercycle and AI capex tailwinds over 6M and YTD. Cybersecurity holdings (Cisco ~4%) provided some defensive ballast during the chip rotation.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "78% of 52-week range.",
      "aumFlow": "AUM EUR 7,685M (+7.8% 1M). Implied flow +5.9pp vs return — net inflows beyond price effect.",
      "topHoldings": "Micron Technology ~11%, Samsung Electronics Co., Ltd. ~9%, SK hynix, Inc. ~9%, Intel Corp. ~6%, Cisco Systems, Inc. ~4% — top 10 = ~57%."
    },
    {
      "ticker": "IQQH",
      "name": "iShares Global Clean Energy Transition UCITS ETF USD (Dist)",
      "pct1m": -6.84,
      "pct6m": -5.05,
      "pctYtd": 8.4,
      "aumEurM": 2716,
      "holds": "The iShares Global Clean Energy Transition UCITS ETF USD (Dist) seeks to track the S&P Global Clean Energy Transition index. The S&P Global Clean Energy Transition index tracks the largest and most liquid stocks worldwide which are involved in clean energy business.",
      "whyItMoved": "Rising oil prices (Brent touching $90 on Iran tensions) and Treasury yields hit rate-sensitive clean-energy names hard in August (-6.8%). The 6M decline (-5%) reflects broader sector volatility, though YTD remains positive (+8.4%) thanks to early-2026 clean-energy ETF gains of 25-30% before the recent reversal. Bloom Energy (~15% weight) and First Solar (~8%) amplified both swings.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "37% of 52-week range.",
      "aumFlow": "AUM EUR 2,716M (+3.5% 1M). Implied flow +10.3pp vs return — net inflows beyond price effect.",
      "topHoldings": "Bloom Energy ~15%, First Solar ~8%, Nextpower ~7%, China Yangtze Power Co., Ltd. ~6%, Enphase Energy ~5% — top 10 = ~55%."
    },
    {
      "ticker": "EQQQ",
      "name": "Invesco EQQQ Nasdaq-100 UCITS ETF",
      "pct1m": -1.73,
      "pct6m": 18.16,
      "pctYtd": 16.9,
      "aumEurM": 11757,
      "holds": "The Invesco EQQQ Nasdaq-100 UCITS ETF seeks to track the Nasdaq 100® index. The Nasdaq 100® index tracks a selection of 100 stocks chosen from among non-financial stocks listed on the NASDAQ stock exchange.",
      "whyItMoved": "Rising Treasury yields, Middle East tensions (Brent crude at $90), and the semiconductor sell-off drove the 1M dip. Nasdaq 100 fell to ~29,347 before stabilising ahead of Jackson Hole. YTD +17% and 6M +18% supported by AI capex momentum, though broader diversification diluted the pure AI/semi gains seen in concentrated peers.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "78% of 52-week range.",
      "aumFlow": "AUM EUR 11,757M (+8.9% 1M). Implied flow +10.6pp vs return — net inflows beyond price effect.",
      "topHoldings": "NVIDIA Corp. ~8%, Apple ~7%, Micron Technology ~6%, Microsoft Corp ~4%, Amazon.com, Inc. ~4% — top 10 = ~45%."
    },
    {
      "ticker": "IQQK",
      "name": "iShares MSCI Korea UCITS ETF (Dist)",
      "pct1m": 5.12,
      "pct6m": 30.23,
      "pctYtd": 84.27,
      "aumEurM": 977,
      "holds": "The iShares MSCI Korea UCITS ETF (Dist) seeks to track the MSCI Korea 20/35 index. The MSCI Korea 20/35 index tracks large and mid cap Korean stocks. The weight of the largest constituent is constrained to 35% and the weights of all other constituents are constrained to a maximum of 20%.",
      "whyItMoved": "HBM memory supercycle drove KOSPI up 47%+ YTD: Samsung (~29%) and SK Hynix (~18%) produce the bulk of high-bandwidth memory for AI accelerators. Corporate governance reforms attracted massive foreign inflows. August's +5.1% bucked the broader chip sell-off as Korean memory names rallied on strong Q2 NAND revenue data.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "74% of 52-week range.",
      "aumFlow": "AUM EUR 977M (+18.1% 1M). Implied flow +13.0pp vs return — net inflows beyond price effect.",
      "topHoldings": "Samsung Electronics Co., Ltd. ~29%, SK hynix, Inc. ~18%, SK Square Co. Ltd. ~6%, Samsung Electro-Mechanics Co., Ltd. ~4%, Samsung Electronics Co., Ltd. ~3% — top 10 = ~69%."
    },
    {
      "ticker": "WTE",
      "name": "WisdomTree Physical Palladium",
      "pct1m": 2.52,
      "pct6m": -21.79,
      "pctYtd": -14.34,
      "holds": "The palladium spot price is the price of palladium in US Dollar.",
      "whyItMoved": "Palladium shifted into surplus after 14 consecutive deficit years — UBS cut its price target to $1,100/oz. EV transition is eroding autocatalyst demand (the metal's primary use case), while ETF holdings declined and recycling supply increased. The 1M bounce (+2.5%) reflects a short-term oversold reversal within a structurally bearish setup.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "25% of 52-week range.",
      "aumFlow": "AUM not published."
    }
  ]
};
