// etf_data.js
// ETF News — weekly data file.
// Replaced every Thursday during the live pipeline run. index.html reads this
// and never needs to change. Generated by update_etf_data.py from justETF
// data (EUR); whyItMoved researched fields are filled in by Claude afterwards.

const LEDGER_DATA = {
  "meta": {
    "asOf": "20 Jul 2026, close",
    "fundsTracked": 272,
    "matchedFunds": 258
  },
  "performers": {
    "1m": {
      "best": [
        {
          "tier": "researched",
          "ticker": "CYSE",
          "name": "WisdomTree Cybersecurity",
          "category": "Cybersecurity stocks",
          "pct": 22.61,
          "holds": "WisdomTree Cybersecurity — Cybersecurity stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Cybersecurity stocks category average (+22.6%) by ~0pts over 1M.",
          "returnRisk": "0.8 return/risk (1Y, EUR); 1Y volatility 33%.",
          "week52": "94% of 52-week range.",
          "aumFlow": "AUM EUR 407M — flow baseline being established (first tracked period).",
          "aumEurM": 407,
          "whyItMoved": "Cybersecurity stocks surged in July after IBM's CEO flagged cyber threats as a top customer priority, signaling security budgets are becoming non-discretionary. The fund's top holdings CrowdStrike (+11%) and Palo Alto Networks (+7%) led a sector-wide rally on July 14 as fears of AI-powered cyberattacks boosted demand for pure-play security vendors.",
          "topHoldings": "CrowdStrike Holdings ~8%, Datadog ~7%, SentinelOne ~7%, Fortinet Inc ~6%, Palo Alto Networks ~6% — top 10 = ~56%."
        },
        {
          "tier": "researched",
          "ticker": "IUKP",
          "name": "iShares UK Property",
          "category": "UK property stocks",
          "pct": 12.13,
          "holds": "iShares UK Property — UK property stocks fund on the Lightyear list. ~28 holdings.",
          "vsCategory": "Outperformed the UK property stocks category average (+12.1%) by ~0pts over 1M.",
          "returnRisk": "0.8 return/risk (1Y, EUR); 1Y volatility 20%.",
          "week52": "100% of 52-week range.",
          "aumFlow": "AUM EUR 521M — flow baseline being established (first tracked period).",
          "aumEurM": 521,
          "whyItMoved": "UK property stocks rallied with logistics REITs leading, as the fund's largest holding SEGRO (~20%) lifted the sector on the FTSE 250 amid strong rental growth in warehouse and logistics assets. Improving investor confidence in commercial property valuations supported broader REIT gains despite the BoE holding rates at 3.75%.",
          "topHoldings": "SEGRO ~20%, Land Securities Group ~10%, LondonMetric Property Plc ~9%, The British Land ~8%, Tritax Big Box REIT ~8% — top 10 = ~76%."
        },
        {
          "tier": "screener",
          "ticker": "IESU",
          "name": "iShares S&P 500 Energy Sector",
          "category": "US energy stocks",
          "pct": 9.48,
          "holds": "iShares S&P 500 Energy Sector — US energy stocks fund on the Lightyear list. ~21 holdings.",
          "vsCategory": "Outperformed the US energy stocks category average (+9.5%) by ~0pts over 1M.",
          "returnRisk": "1.9 return/risk (1Y, EUR); 1Y volatility 23%.",
          "week52": "83% of 52-week range.",
          "aumFlow": "AUM EUR 1,242M — flow baseline being established (first tracked period).",
          "aumEurM": 1242
        },
        {
          "tier": "screener",
          "ticker": "BTEC",
          "name": "iShares Nasdaq US Biotechnology",
          "category": "US biotech stocks",
          "pct": 8.46,
          "holds": "iShares Nasdaq US Biotechnology — US biotech stocks fund on the Lightyear list. ~253 holdings.",
          "vsCategory": "Outperformed the US biotech stocks category average (+8.5%) by ~0pts over 1M.",
          "returnRisk": "2.7 return/risk (1Y, EUR); 1Y volatility 19%.",
          "week52": "87% of 52-week range.",
          "aumFlow": "AUM EUR 953M — flow baseline being established (first tracked period).",
          "aumEurM": 953
        },
        {
          "tier": "screener",
          "ticker": "2B78",
          "name": "iShares Healthcare Innovation",
          "category": "Global healthcare stocks / Healthcare stocks",
          "pct": 7.56,
          "holds": "iShares Healthcare Innovation — Global healthcare stocks / Healthcare stocks fund on the Lightyear list. ~168 holdings.",
          "vsCategory": "No category average available this run.",
          "returnRisk": "1.9 return/risk (1Y, EUR); 1Y volatility 15%.",
          "week52": "88% of 52-week range.",
          "aumFlow": "AUM EUR 991M — flow baseline being established (first tracked period).",
          "aumEurM": 991
        }
      ],
      "worst": [
        {
          "tier": "researched",
          "ticker": "SEC0",
          "name": "iShares MSCI Global Semiconductors",
          "category": "Global semiconductor stocks",
          "pct": -16.3,
          "holds": "iShares MSCI Global Semiconductors — Global semiconductor stocks fund on the Lightyear list. ~261 holdings.",
          "vsCategory": "Outperformed the Global semiconductor stocks category average (-16.3%) by ~0pts over 1M.",
          "returnRisk": "4.1 return/risk (1Y, EUR); 1Y volatility 34%.",
          "week52": "72% of 52-week range.",
          "aumFlow": "AUM EUR 4,902M — flow baseline being established (first tracked period).",
          "aumEurM": 4902,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "Semiconductor stocks sold off sharply as investors questioned AI capital expenditure growth, erasing $1.3 trillion in sector market value. Top holding Micron (~9%) fell ~17% on fears that AI processing supply is catching up to demand, while Intel's 18A foundry yield delays and DeepSeek's proprietary chip plans added pressure.",
          "topHoldings": "Micron Technology ~9%, AMD ~8%, Broadcom Inc. ~7%, Taiwan Semiconductor Manufacturing Co., Ltd. ~7%, NVIDIA Corp. ~6% — top 10 = ~59%."
        },
        {
          "tier": "researched",
          "ticker": "SMGB",
          "name": "VanEck Semiconductor",
          "category": "Semiconductors / US semiconductor stocks",
          "pct": -13.63,
          "holds": "VanEck Semiconductor — Semiconductors / US semiconductor stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Semiconductors / US semiconductor stocks category average (-13.6%) by ~0pts over 1M.",
          "returnRisk": "3.2 return/risk (1Y, EUR); 1Y volatility 39%.",
          "week52": "75% of 52-week range.",
          "aumFlow": "AUM EUR 7,291M — flow baseline being established (first tracked period).",
          "aumEurM": 7291,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "The concentrated 25-stock fund fell sharply alongside the broader semiconductor selloff as Wall Street questioned AI capex sustainability. Top holdings Micron (~14%) and AMD (~12%) led the decline amid reports that Meta is renting out excess compute capacity, signaling AI processing supply may be catching up to demand.",
          "topHoldings": "Micron Technology ~14%, AMD ~12%, Broadcom Inc. ~8%, Intel Corp. ~8%, Taiwan Semiconductor Manufacturing Co., Ltd. ~8% — top 10 = ~80%."
        },
        {
          "tier": "screener",
          "ticker": "84X0",
          "name": "iShares MSCI EM ex-China",
          "category": "Emerging markets stocks ex-China",
          "pct": -10.84,
          "holds": "iShares MSCI EM ex-China — Emerging markets stocks ex-China fund on the Lightyear list. ~605 holdings.",
          "vsCategory": "Outperformed the Emerging markets stocks ex-China category average (-10.8%) by ~0pts over 1M.",
          "returnRisk": "1.9 return/risk (1Y, EUR); 1Y volatility 27%.",
          "week52": "72% of 52-week range.",
          "aumFlow": "AUM EUR 4,807M — flow baseline being established (first tracked period).",
          "aumEurM": 4807
        },
        {
          "tier": "screener",
          "ticker": "CEA1",
          "name": "iShares MSCI EM Asia",
          "category": "Emerging Asian markets stocks",
          "pct": -9.35,
          "holds": "iShares MSCI EM Asia — Emerging Asian markets stocks fund on the Lightyear list. ~968 holdings.",
          "vsCategory": "Outperformed the Emerging Asian markets stocks category average (-9.6%) by ~0pts over 1M.",
          "returnRisk": "1.7 return/risk (1Y, EUR); 1Y volatility 23%.",
          "week52": "71% of 52-week range.",
          "aumFlow": "AUM EUR 7,166M — flow baseline being established (first tracked period).",
          "aumEurM": 7166
        },
        {
          "tier": "screener",
          "ticker": "AYEM",
          "name": "iShares MSCI EM IMI Screened",
          "category": "Emerging markets stocks",
          "pct": -8.61,
          "holds": "iShares MSCI EM IMI Screened — Emerging markets stocks fund on the Lightyear list. ~2585 holdings.",
          "vsCategory": "Underperformed the Emerging markets stocks category average (-6.7%) by ~2pts over 1M.",
          "returnRisk": "1.7 return/risk (1Y, EUR); 1Y volatility 19%.",
          "week52": "71% of 52-week range.",
          "aumFlow": "AUM EUR 5,525M — flow baseline being established (first tracked period).",
          "aumEurM": 5525
        }
      ]
    },
    "6m": {
      "best": [
        {
          "tier": "researched",
          "ticker": "SEC0",
          "name": "iShares MSCI Global Semiconductors",
          "category": "Global semiconductor stocks",
          "pct": 62.3,
          "holds": "iShares MSCI Global Semiconductors — Global semiconductor stocks fund on the Lightyear list. ~261 holdings.",
          "vsCategory": "Outperformed the Global semiconductor stocks category average (+62.3%) by ~0pts over 6M.",
          "returnRisk": "4.1 return/risk (1Y, EUR); 1Y volatility 34%.",
          "week52": "72% of 52-week range.",
          "aumFlow": "AUM EUR 4,902M — flow baseline being established (first tracked period).",
          "aumEurM": 4902,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "The fund surged over six months on the AI-driven semiconductor supercycle, with top holdings Micron, AMD, and Broadcom benefiting from explosive demand for high-bandwidth memory and AI accelerators. Despite the late-period selloff, the PHLX Semiconductor Index still finished Q2 up 88% from its lows.",
          "topHoldings": "Micron Technology ~9%, AMD ~8%, Broadcom Inc. ~7%, Taiwan Semiconductor Manufacturing Co., Ltd. ~7%, NVIDIA Corp. ~6% — top 10 = ~59%."
        },
        {
          "tier": "researched",
          "ticker": "SMGB",
          "name": "VanEck Semiconductor",
          "category": "Semiconductors / US semiconductor stocks",
          "pct": 59.2,
          "holds": "VanEck Semiconductor — Semiconductors / US semiconductor stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Semiconductors / US semiconductor stocks category average (+59.2%) by ~0pts over 6M.",
          "returnRisk": "3.2 return/risk (1Y, EUR); 1Y volatility 39%.",
          "week52": "75% of 52-week range.",
          "aumFlow": "AUM EUR 7,291M — flow baseline being established (first tracked period).",
          "aumEurM": 7291,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "The fund's concentrated exposure to 25 semiconductor names amplified gains from the AI memory supercycle, with top holdings Micron (~14%) and AMD (~12%) driving outsized returns. SK Hynix's HBM dominance and Samsung's memory-chip recovery added tailwinds across the portfolio.",
          "topHoldings": "Micron Technology ~14%, AMD ~12%, Broadcom Inc. ~8%, Intel Corp. ~8%, Taiwan Semiconductor Manufacturing Co., Ltd. ~8% — top 10 = ~80%."
        },
        {
          "tier": "screener",
          "ticker": "CYSE",
          "name": "WisdomTree Cybersecurity",
          "category": "Cybersecurity stocks",
          "pct": 51.34,
          "holds": "WisdomTree Cybersecurity — Cybersecurity stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Cybersecurity stocks category average (+51.3%) by ~0pts over 6M.",
          "returnRisk": "0.8 return/risk (1Y, EUR); 1Y volatility 33%.",
          "week52": "94% of 52-week range.",
          "aumFlow": "AUM EUR 407M — flow baseline being established (first tracked period).",
          "aumEurM": 407
        },
        {
          "tier": "screener",
          "ticker": "IKOR",
          "name": "iShares MSCI Korea",
          "category": "Korean stocks",
          "pct": 50.09,
          "holds": "iShares MSCI Korea — Korean stocks fund on the Lightyear list. ~78 holdings.",
          "vsCategory": "Outperformed the Korean stocks category average (+50.1%) by ~0pts over 6M.",
          "returnRisk": "2.8 return/risk (1Y, EUR); 1Y volatility 51%.",
          "week52": "66% of 52-week range.",
          "aumFlow": "AUM EUR 949M — flow baseline being established (first tracked period).",
          "aumEurM": 949
        },
        {
          "tier": "screener",
          "ticker": "LSMC",
          "name": "Amundi MSCI Semiconductors",
          "category": "Semiconductor industry stocks",
          "pct": 45.75,
          "holds": "Amundi MSCI Semiconductors — Semiconductor industry stocks fund on the Lightyear list. ~65 holdings.",
          "vsCategory": "Outperformed the Semiconductor industry stocks category average (+45.8%) by ~0pts over 6M.",
          "returnRisk": "3.0 return/risk (1Y, EUR); 1Y volatility 30%.",
          "week52": "76% of 52-week range.",
          "aumFlow": "AUM EUR 1,869M — flow baseline being established (first tracked period).",
          "aumEurM": 1869
        }
      ],
      "worst": [
        {
          "tier": "researched",
          "ticker": "DFEN",
          "name": "VanEck Defense",
          "category": "Defence stocks / Defense stocks",
          "pct": -19.49,
          "holds": "VanEck Defense — Defence stocks / Defense stocks fund on the Lightyear list. ~40 holdings.",
          "vsCategory": "Outperformed the Defence stocks / Defense stocks category average (-19.5%) by ~0pts over 6M.",
          "returnRisk": "0.0 return/risk (1Y, EUR); 1Y volatility 24%.",
          "week52": "15% of 52-week range.",
          "aumFlow": "AUM EUR 6,051M — flow baseline being established (first tracked period).",
          "aumEurM": 6051,
          "whyItMoved": "Defense stocks entered a prolonged consolidation after their exceptional 2025 rally, with the 6M decline driven by underwhelming Q1 earnings from key European constituents including Rheinmetall. Analysts noted that increased military spending commitments were already priced into valuations after the sector's strong 2025 performance.",
          "topHoldings": "Palantir Technologies, Inc. ~9%, RTX ~7%, Thales SA ~7%, Leonardo SpA ~7%, Elbit Systems ~6% — top 10 = ~59%."
        },
        {
          "tier": "researched",
          "ticker": "EUDF",
          "name": "WisdomTree Europe Defence",
          "category": "European defence stocks / European defense stocks",
          "pct": -14.5,
          "holds": "WisdomTree Europe Defence — European defence stocks / European defense stocks fund on the Lightyear list. ~37 holdings.",
          "vsCategory": "Outperformed the European defence stocks / European defense stocks category average (-14.5%) by ~0pts over 6M.",
          "returnRisk": "-0.1 return/risk (1Y, EUR); 1Y volatility 28%.",
          "week52": "30% of 52-week range.",
          "aumFlow": "AUM EUR 4,162M — flow baseline being established (first tracked period).",
          "aumEurM": 4162,
          "whyItMoved": "European defense stocks pulled back sharply from their 2025 military spending highs, as underwhelming Q1 results from Rheinmetall (~11% weight) led investors to question the sector's valuation premium. The concentrated European-only portfolio amplified the correction, with Thales, BAE Systems, and Airbus all declining.",
          "topHoldings": "Thales SA ~13%, BAE Systems ~12%, Rheinmetall AG ~11%, Airbus SE ~8%, Rolls-Royce Holdings ~8% — top 9 = ~78%."
        },
        {
          "tier": "screener",
          "ticker": "IIND",
          "name": "iShares MSCI India",
          "category": "Indian stocks",
          "pct": -3.64,
          "holds": "iShares MSCI India — Indian stocks fund on the Lightyear list. ~167 holdings.",
          "vsCategory": "Outperformed the Indian stocks category average (-3.6%) by ~0pts over 6M.",
          "returnRisk": "-0.6 return/risk (1Y, EUR); 1Y volatility 16%.",
          "week52": "41% of 52-week range.",
          "aumFlow": "AUM EUR 4,485M — flow baseline being established (first tracked period).",
          "aumEurM": 4485
        },
        {
          "tier": "screener",
          "ticker": "SEGA",
          "name": "iShares Core Euro Government Bond",
          "category": "Eurozone government bonds",
          "pct": -0.7,
          "holds": "iShares Core Euro Government Bond — Eurozone government bonds fund on the Lightyear list. ~550 holdings.",
          "vsCategory": "Outperformed the Eurozone government bonds category average (-0.8%) by ~0pts over 6M.",
          "returnRisk": "0.1 return/risk (1Y, EUR); 1Y volatility 4%.",
          "week52": "30% of 52-week range.",
          "aumFlow": "AUM EUR 5,333M — flow baseline being established (first tracked period).",
          "aumEurM": 5333
        },
        {
          "tier": "screener",
          "ticker": "VECP",
          "name": "Vanguard EUR Corporate Bond",
          "category": "Eurozone corporate bonds",
          "pct": -0.17,
          "holds": "Vanguard EUR Corporate Bond — Eurozone corporate bonds fund on the Lightyear list. ~3538 holdings.",
          "vsCategory": "Underperformed the Eurozone corporate bonds category average (+0.0%) by ~0pts over 6M.",
          "returnRisk": "0.4 return/risk (1Y, EUR); 1Y volatility 3%.",
          "week52": "57% of 52-week range.",
          "aumFlow": "AUM EUR 3,266M — flow baseline being established (first tracked period).",
          "aumEurM": 3266
        }
      ]
    },
    "ytd": {
      "best": [
        {
          "tier": "researched",
          "ticker": "SEC0",
          "name": "iShares MSCI Global Semiconductors",
          "category": "Global semiconductor stocks",
          "pct": 83.4,
          "holds": "iShares MSCI Global Semiconductors — Global semiconductor stocks fund on the Lightyear list. ~261 holdings.",
          "vsCategory": "Outperformed the Global semiconductor stocks category average (+83.4%) by ~0pts over YTD.",
          "returnRisk": "4.1 return/risk (1Y, EUR); 1Y volatility 34%.",
          "week52": "72% of 52-week range.",
          "aumFlow": "AUM EUR 4,902M — flow baseline being established (first tracked period).",
          "aumEurM": 4902,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "Year-to-date gains of +83.4% reflect the first-half semiconductor supercycle driven by surging AI infrastructure spending, with data center capex projected to top $1 trillion in 2026. Top holdings Micron, AMD, and Broadcom all posted outsized gains on HBM and AI accelerator demand before the July correction.",
          "topHoldings": "Micron Technology ~9%, AMD ~8%, Broadcom Inc. ~7%, Taiwan Semiconductor Manufacturing Co., Ltd. ~7%, NVIDIA Corp. ~6% — top 10 = ~59%."
        },
        {
          "tier": "researched",
          "ticker": "SMGB",
          "name": "VanEck Semiconductor",
          "category": "Semiconductors / US semiconductor stocks",
          "pct": 77.67,
          "holds": "VanEck Semiconductor — Semiconductors / US semiconductor stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Semiconductors / US semiconductor stocks category average (+77.7%) by ~0pts over YTD.",
          "returnRisk": "3.2 return/risk (1Y, EUR); 1Y volatility 39%.",
          "week52": "75% of 52-week range.",
          "aumFlow": "AUM EUR 7,291M — flow baseline being established (first tracked period).",
          "aumEurM": 7291,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "Year-to-date performance reflects the first-half AI infrastructure boom, with the fund's concentrated semiconductor portfolio benefiting from exploding demand for AI storage and high-bandwidth memory. Top holdings Micron and AMD posted outsized gains, though the late-July selloff shaved returns from the June peak.",
          "topHoldings": "Micron Technology ~14%, AMD ~12%, Broadcom Inc. ~8%, Intel Corp. ~8%, Taiwan Semiconductor Manufacturing Co., Ltd. ~8% — top 10 = ~80%."
        },
        {
          "tier": "screener",
          "ticker": "IKOR",
          "name": "iShares MSCI Korea",
          "category": "Korean stocks",
          "pct": 72.1,
          "holds": "iShares MSCI Korea — Korean stocks fund on the Lightyear list. ~78 holdings.",
          "vsCategory": "Outperformed the Korean stocks category average (+72.1%) by ~0pts over YTD.",
          "returnRisk": "2.8 return/risk (1Y, EUR); 1Y volatility 51%.",
          "week52": "66% of 52-week range.",
          "aumFlow": "AUM EUR 949M — flow baseline being established (first tracked period).",
          "aumEurM": 949
        },
        {
          "tier": "screener",
          "ticker": "ITWN",
          "name": "iShares MSCI Taiwan",
          "category": "Taiwan large and mid-cap stocks",
          "pct": 56.47,
          "holds": "iShares MSCI Taiwan — Taiwan large and mid-cap stocks fund on the Lightyear list. ~78 holdings.",
          "vsCategory": "Outperformed the Taiwan large and mid-cap stocks category average (+56.5%) by ~0pts over YTD.",
          "returnRisk": "2.8 return/risk (1Y, EUR); 1Y volatility 28%.",
          "week52": "76% of 52-week range.",
          "aumFlow": "AUM EUR 1,260M — flow baseline being established (first tracked period).",
          "aumEurM": 1260
        },
        {
          "tier": "screener",
          "ticker": "LSMC",
          "name": "Amundi MSCI Semiconductors",
          "category": "Semiconductor industry stocks",
          "pct": 55.21,
          "holds": "Amundi MSCI Semiconductors — Semiconductor industry stocks fund on the Lightyear list. ~65 holdings.",
          "vsCategory": "Outperformed the Semiconductor industry stocks category average (+55.2%) by ~0pts over YTD.",
          "returnRisk": "3.0 return/risk (1Y, EUR); 1Y volatility 30%.",
          "week52": "76% of 52-week range.",
          "aumFlow": "AUM EUR 1,869M — flow baseline being established (first tracked period).",
          "aumEurM": 1869
        }
      ],
      "worst": [
        {
          "tier": "researched",
          "ticker": "IIND",
          "name": "iShares MSCI India",
          "category": "Indian stocks",
          "pct": -7.92,
          "holds": "iShares MSCI India — Indian stocks fund on the Lightyear list. ~167 holdings.",
          "vsCategory": "Outperformed the Indian stocks category average (-7.9%) by ~0pts over YTD.",
          "returnRisk": "-0.6 return/risk (1Y, EUR); 1Y volatility 16%.",
          "week52": "41% of 52-week range.",
          "aumFlow": "AUM EUR 4,485M — flow baseline being established (first tracked period).",
          "aumEurM": 4485,
          "whyItMoved": "India underperformed sharply as global capital rotated toward AI- and semiconductor-heavy markets, pushing India's MSCI EM weight from ~20% to ~11%. Foreign portfolio investors withdrew ~$30 billion YTD while crude oil above $100/bbl weighed on the import-dependent economy and the rupee depreciated ~6%.",
          "topHoldings": "HDFC Bank Ltd. ~6%, Reliance Industries Ltd. ~6%, ICICI Bank Ltd. ~5%, Bharti Airtel Ltd. ~4%, Infosys Ltd. ~3% — top 10 = ~34%."
        },
        {
          "tier": "researched",
          "ticker": "DFEN",
          "name": "VanEck Defense",
          "category": "Defence stocks / Defense stocks",
          "pct": -2.87,
          "holds": "VanEck Defense — Defence stocks / Defense stocks fund on the Lightyear list. ~40 holdings.",
          "vsCategory": "Outperformed the Defence stocks / Defense stocks category average (-2.9%) by ~0pts over YTD.",
          "returnRisk": "0.0 return/risk (1Y, EUR); 1Y volatility 24%.",
          "week52": "15% of 52-week range.",
          "aumFlow": "AUM EUR 6,051M — flow baseline being established (first tracked period).",
          "aumEurM": 6051,
          "whyItMoved": "After a strong 2025 rally on European rearmament spending, defense stocks gave back gains as Q1 earnings disappointed and investors questioned further upside. The fund's top holding Palantir (~9%) helped offset broader weakness, but European defense names like Thales and Leonardo dragged on returns.",
          "topHoldings": "Palantir Technologies, Inc. ~9%, RTX ~7%, Thales SA ~7%, Leonardo SpA ~7%, Elbit Systems ~6% — top 10 = ~59%."
        },
        {
          "tier": "screener",
          "ticker": "SEGA",
          "name": "iShares Core Euro Government Bond",
          "category": "Eurozone government bonds",
          "pct": -0.35,
          "holds": "iShares Core Euro Government Bond — Eurozone government bonds fund on the Lightyear list. ~550 holdings.",
          "vsCategory": "Outperformed the Eurozone government bonds category average (-0.4%) by ~0pts over YTD.",
          "returnRisk": "0.1 return/risk (1Y, EUR); 1Y volatility 4%.",
          "week52": "30% of 52-week range.",
          "aumFlow": "AUM EUR 5,333M — flow baseline being established (first tracked period).",
          "aumEurM": 5333
        },
        {
          "tier": "screener",
          "ticker": "VECP",
          "name": "Vanguard EUR Corporate Bond",
          "category": "Eurozone corporate bonds",
          "pct": 0.16,
          "holds": "Vanguard EUR Corporate Bond — Eurozone corporate bonds fund on the Lightyear list. ~3538 holdings.",
          "vsCategory": "Underperformed the Eurozone corporate bonds category average (+0.4%) by ~0pts over YTD.",
          "returnRisk": "0.4 return/risk (1Y, EUR); 1Y volatility 3%.",
          "week52": "57% of 52-week range.",
          "aumFlow": "AUM EUR 3,266M — flow baseline being established (first tracked period).",
          "aumEurM": 3266
        },
        {
          "tier": "screener",
          "ticker": "OM3F",
          "name": "iShares EUR Corporate Bond ESG",
          "category": "ESG Euro corporate bonds",
          "pct": 0.43,
          "holds": "iShares EUR Corporate Bond ESG — ESG Euro corporate bonds fund on the Lightyear list. ~3173 holdings.",
          "vsCategory": "Underperformed the ESG Euro corporate bonds category average (+0.6%) by ~0pts over YTD.",
          "returnRisk": "0.4 return/risk (1Y, EUR); 1Y volatility 3%.",
          "week52": "69% of 52-week range.",
          "aumFlow": "AUM EUR 4,129M — flow baseline being established (first tracked period).",
          "aumEurM": 4129
        }
      ]
    }
  },
  "portfolio": [
    {
      "ticker": "SEC0",
      "name": "iShares MSCI Global Semiconductors UCITS ETF USD (Acc)",
      "pct1m": -16.3,
      "pct6m": 62.3,
      "pctYtd": 83.4,
      "aumEurM": 4902,
      "holds": "The iShares MSCI Global Semiconductors UCITS ETF USD (Acc) seeks to track the MSCI ACWI IMI Semiconductors & Semiconductor Equipment ESG Screened Select Capped index. The MSCI ACWI IMI Semiconductors & Semiconductor Equipment ESG Screened Select Capped index tracks large, mid and small cap companies across 23 Developed Markets and 24 Emerging Markets that are active in the semiconductor industry. The stocks included are filtered according to ESG criteria (environmental, social and corporate governance).",
      "whyItMoved": "Semiconductors rallied +83% YTD on the AI infrastructure supercycle but pulled back -16% in the last month as investors questioned AI capex sustainability and Intel's foundry yields disappointed. Top holdings Micron (~9%), AMD (~8%), and Broadcom (~7%) are heavily exposed to the AI memory cycle's boom and recent correction.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "72% of 52-week range.",
      "aumFlow": "AUM EUR 4,902M — flow baseline being established (first tracked period).",
      "topHoldings": "Micron Technology ~9%, AMD ~8%, Broadcom Inc. ~7%, Taiwan Semiconductor Manufacturing Co., Ltd. ~7%, NVIDIA Corp. ~6% — top 10 = ~59%."
    },
    {
      "ticker": "AIFS",
      "name": "iShares AI Infrastructure UCITS ETF USD (Acc)",
      "pct1m": -9.71,
      "pct6m": 42.13,
      "pctYtd": 48.79,
      "aumEurM": 919,
      "holds": "The iShares AI Infrastructure UCITS ETF USD (Acc) seeks to track the STOXX Global AI Infrastructure index. The STOXX Global AI Infrastructure index tracks the performance of companies worldwide that are engaged in the field of AI infrastructure. The stocks included are filtered according to ESG criteria (environmental, social and corporate governance).",
      "whyItMoved": "The fund gained +49% YTD on surging AI infrastructure spending, with global data center capex projected to top $1 trillion in 2026. Top holdings AMD (~8%) and Intel (~8%) benefited from the buildout, though the July semiconductor selloff pulled the 1M return to -9.7%.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "80% of 52-week range.",
      "aumFlow": "AUM EUR 919M — flow baseline being established (first tracked period).",
      "topHoldings": "AMD ~8%, Intel Corp. ~8%, Micron Technology ~7%, Cisco Systems, Inc. ~5%, Samsung Electronics Co., Ltd. ~4% — top 10 = ~51%."
    },
    {
      "ticker": "XAIX",
      "name": "Xtrackers Artificial Intelligence & Big Data UCITS ETF 1C",
      "pct1m": -8.57,
      "pct6m": 29.37,
      "pctYtd": 27.47,
      "aumEurM": 7356,
      "holds": "The Xtrackers Artificial Intelligence & Big Data UCITS ETF 1C seeks to track the Nasdaq Global Artificial Intelligence and Big Data index. The Nasdaq Global Artificial Intelligence and Big Data index tracks international companies of the sectors artificial intelligence, big data and cyber security. The stocks included are filtered according to ESG criteria (environmental, social and corporate governance).",
      "whyItMoved": "The fund rose +27% YTD as its diversified AI exposure including Micron (~9%), Samsung (~8%), and SK hynix (~8%) captured the HBM memory supercycle. The July chip selloff drove the 1M loss of -8.6%, reflecting the portfolio's heavy semiconductor tilt.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "72% of 52-week range.",
      "aumFlow": "AUM EUR 7,356M — flow baseline being established (first tracked period).",
      "topHoldings": "Micron Technology ~9%, Samsung Electronics Co., Ltd. ~8%, SK hynix, Inc. ~8%, Intel Corp. ~5%, Cisco Systems, Inc. ~4% — top 10 = ~54%."
    },
    {
      "ticker": "IQQH",
      "name": "iShares Global Clean Energy Transition UCITS ETF USD (Dist)",
      "pct1m": -13.6,
      "pct6m": 7.04,
      "pctYtd": 14.62,
      "aumEurM": 2846,
      "holds": "The iShares Global Clean Energy Transition UCITS ETF USD (Dist) seeks to track the S&P Global Clean Energy Transition index. The S&P Global Clean Energy Transition index tracks the largest and most liquid stocks worldwide which are involved in clean energy business.",
      "whyItMoved": "Clean energy stocks posted a mixed 2026 with the fund up +15% YTD, navigating a complicated policy environment for renewables. Top holdings Bloom Energy (~12%) and First Solar (~10%) supported gains, but the 1M pullback of -13.6% tracked the broader tech selloff.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "51% of 52-week range.",
      "aumFlow": "AUM EUR 2,846M — flow baseline being established (first tracked period).",
      "topHoldings": "Bloom Energy ~12%, First Solar ~10%, Nextpower ~8%, Enphase Energy ~6%, China Yangtze Power Co., Ltd. ~5% — top 10 = ~55%."
    },
    {
      "ticker": "EQQQ",
      "name": "Invesco EQQQ Nasdaq-100 UCITS ETF",
      "pct1m": -4.67,
      "pct6m": 18.78,
      "pctYtd": 17.76,
      "aumEurM": 11445,
      "holds": "The Invesco EQQQ Nasdaq-100 UCITS ETF seeks to track the Nasdaq 100® index. The Nasdaq 100® index tracks a selection of 100 stocks chosen from among non-financial stocks listed on the NASDAQ stock exchange.",
      "whyItMoved": "The Nasdaq-100 gained +18% YTD driven by AI infrastructure spending and tech earnings strength, posting its best first half since 2023. The 1M pullback of -4.7% reflected the chip selloff, with top holding NVIDIA (~8%) volatile amid AI capex concerns.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "81% of 52-week range.",
      "aumFlow": "AUM EUR 11,445M — flow baseline being established (first tracked period).",
      "topHoldings": "NVIDIA Corp. ~8%, Apple ~7%, Microsoft ~5%, Amazon.com, Inc. ~5%, Micron Technology ~5% — top 10 = ~47%."
    },
    {
      "ticker": "IQQK",
      "name": "iShares MSCI Korea UCITS ETF (Dist)",
      "pct1m": -22.87,
      "pct6m": 50.09,
      "pctYtd": 72.1,
      "aumEurM": 949,
      "holds": "The iShares MSCI Korea UCITS ETF (Dist) seeks to track the MSCI Korea 20/35 index. The MSCI Korea 20/35 index tracks large and mid cap Korean stocks. The weight of the largest constituent is constrained to 35% and the weights of all other constituents are constrained to a maximum of 20%.",
      "whyItMoved": "South Korea's KOSPI surged as the memory-chip supercycle lifted Samsung (~28%) and SK hynix (~18%), with Korean semiconductor exports jumping 180% in early July. The 1M decline of -23% reflects the KOSPI's 25% tumble from its June peak as leveraged trading amplified volatility.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "66% of 52-week range.",
      "aumFlow": "AUM EUR 949M — flow baseline being established (first tracked period).",
      "topHoldings": "Samsung Electronics Co., Ltd. ~28%, SK hynix, Inc. ~18%, Samsung Electro-Mechanics Co., Ltd. ~4%, SK Square Co. Ltd. ~4%, Hyundai Motor Co. ~3% — top 10 = ~67%."
    },
    {
      "ticker": "WTE",
      "name": "WisdomTree Physical Palladium",
      "pct1m": 2.59,
      "pct6m": -30.06,
      "pctYtd": -16.54,
      "holds": "The palladium spot price is the price of palladium in US Dollar.",
      "whyItMoved": "Palladium declined -17% YTD as the rapid transition to battery-electric vehicles reduces catalytic converter demand, the metal's primary end use. Platinum substitution in remaining ICE applications and increased recycling supply from end-of-life vehicles added further price pressure.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "21% of 52-week range.",
      "aumFlow": "AUM not published."
    }
  ]
};
