// etf_data.js
// ETF News — weekly data file.
// Replaced every Thursday during the live pipeline run. index.html reads this
// and never needs to change. Generated by update_etf_data.py from justETF
// data (EUR); whyItMoved researched fields are filled in by Claude afterwards.

const LEDGER_DATA = {
  "meta": {
    "asOf": "28 Aug 2026, close",
    "fundsTracked": 272,
    "matchedFunds": 258
  },
  "performers": {
    "1m": {
      "best": [
        {
          "tier": "researched",
          "ticker": "AUCO",
          "name": "L&G Gold Mining",
          "category": "Gold mining",
          "pct": 37.63,
          "holds": "L&G Gold Mining — Gold mining fund on the Lightyear list. ~45 holdings.",
          "vsCategory": "Outperformed the Gold mining category average (+37.6%) by ~0pts over 1M.",
          "returnRisk": "1.7 return/risk (1Y, EUR); 1Y volatility 43%.",
          "week52": "81% of 52-week range.",
          "aumFlow": "AUM EUR 831M — flow baseline being established (first tracked period).",
          "aumEurM": 831,
          "whyItMoved": "Gold surged to ~$4,500/oz in August on renewed central-bank buying, softer US payrolls, and reduced Fed tightening expectations. Gold miners outpaced bullion thanks to operating leverage — revenue rises with gold while production costs lag, expanding margins disproportionately.",
          "topHoldings": "Newmont Corp. ~15%, Agnico Eagle Mines Ltd. ~10%, Anglogold Ashanti Plc ~9%, Gold Fields Ltd. ~7%, Kinross Gold Corp. ~6% — top 10 = ~66%."
        },
        {
          "tier": "researched",
          "ticker": "IAUP",
          "name": "iShares Gold Producers",
          "category": "Gold mining stocks",
          "pct": 34.35,
          "holds": "iShares Gold Producers — Gold mining stocks fund on the Lightyear list. ~82 holdings.",
          "vsCategory": "Outperformed the Gold mining stocks category average (+34.4%) by ~0pts over 1M.",
          "returnRisk": "1.7 return/risk (1Y, EUR); 1Y volatility 41%.",
          "week52": "79% of 52-week range.",
          "aumFlow": "AUM EUR 4,220M (+45.8% 1M). Implied flow +11.5pp vs return — net inflows beyond price effect.",
          "aumEurM": 4220,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "Gold's August rally to ~$4,500/oz — driven by weak US jobs data, central-bank accumulation, and easing Fed expectations — lifted miners broadly. GDX surged 21% in a single week with $419M in retail inflows. Newmont and Agnico Eagle, top holdings, saw margin expansion on higher bullion prices.",
          "topHoldings": "Newmont Corp. ~10%, Agnico Eagle Mines Ltd. ~10%, Barrick Mining Corp. ~9%, Wheaton Precious Metals Corp. ~7%, Franco-Nevada ~6% — top 10 = ~61%."
        },
        {
          "tier": "screener",
          "ticker": "CEBT",
          "name": "iShares Essential Metals Producers",
          "category": "Essential metals producers stocks",
          "pct": 21.1,
          "holds": "iShares Essential Metals Producers — Essential metals producers stocks fund on the Lightyear list. ~124 holdings.",
          "vsCategory": "Outperformed the Essential metals producers stocks category average (+21.1%) by ~0pts over 1M.",
          "returnRisk": "2.5 return/risk (1Y, EUR); 1Y volatility 33%.",
          "week52": "93% of 52-week range.",
          "aumFlow": "AUM EUR 915M — flow baseline being established (first tracked period).",
          "aumEurM": 915
        },
        {
          "tier": "screener",
          "ticker": "CEBS",
          "name": "iShares Copper Miners",
          "category": "Copper mining stocks",
          "pct": 19.82,
          "holds": "iShares Copper Miners — Copper mining stocks fund on the Lightyear list. ~43 holdings.",
          "vsCategory": "Outperformed the Copper mining stocks category average (+19.8%) by ~0pts over 1M.",
          "returnRisk": "3.0 return/risk (1Y, EUR); 1Y volatility 33%.",
          "week52": "98% of 52-week range.",
          "aumFlow": "AUM EUR 520M — flow baseline being established (first tracked period).",
          "aumEurM": 520
        },
        {
          "tier": "screener",
          "ticker": "IKOR",
          "name": "iShares MSCI Korea",
          "category": "Korean stocks",
          "pct": 19.54,
          "holds": "iShares MSCI Korea — Korean stocks fund on the Lightyear list. ~77 holdings.",
          "vsCategory": "Outperformed the Korean stocks category average (+19.5%) by ~0pts over 1M.",
          "returnRisk": "2.8 return/risk (1Y, EUR); 1Y volatility 57%.",
          "week52": "78% of 52-week range.",
          "aumFlow": "AUM EUR 1,024M (+23.8% 1M). Implied flow +4.3pp vs return — net inflows beyond price effect.",
          "aumEurM": 1024
        }
      ],
      "worst": [
        {
          "tier": "researched",
          "ticker": "SPYD",
          "name": "SPDR S&P US Dividend Aristocrats",
          "category": "US dividend stocks",
          "pct": -2.71,
          "holds": "SPDR S&P US Dividend Aristocrats — US dividend stocks fund on the Lightyear list. ~155 holdings.",
          "vsCategory": "Underperformed the US dividend stocks category average (-1.6%) by ~1pts over 1M.",
          "returnRisk": "1.3 return/risk (1Y, EUR); 1Y volatility 11%.",
          "week52": "84% of 52-week range.",
          "aumFlow": "AUM EUR 3,378M — flow baseline being established (first tracked period).",
          "aumEurM": 3378,
          "whyItMoved": "Rising US Treasury yields — the 30-year hit a 19-year high of 5.33% — made bonds increasingly competitive versus dividend stocks, pressuring valuations. A strengthening dollar and capital rotation into high-growth tech/AI names further drained interest from defensive dividend plays like Verizon and PepsiCo.",
          "topHoldings": "Verizon Communications ~3%, Accenture Plc ~3%, Realty Income ~2%, PepsiCo, Inc. ~2%, Chevron Corp. ~2% — top 10 = ~20%."
        },
        {
          "tier": "researched",
          "ticker": "IEMB",
          "name": "iShares J.P. Morgan USD Emerging Markets Bond",
          "category": "Emerging markets government bonds",
          "pct": -1.92,
          "holds": "iShares J.P. Morgan USD Emerging Markets Bond — Emerging markets government bonds fund on the Lightyear list. ~619 holdings.",
          "vsCategory": "Underperformed the Emerging markets government bonds category average (-1.2%) by ~1pts over 1M.",
          "returnRisk": "1.3 return/risk (1Y, EUR); 1Y volatility 5%.",
          "week52": "65% of 52-week range.",
          "aumFlow": "AUM EUR 3,730M — flow baseline being established (first tracked period).",
          "aumEurM": 3730,
          "whyItMoved": "The 10-year US Treasury yield surged to a 1.5-year high of 4.75% in August, widening EM credit spreads and pushing down USD-denominated EM bond prices. A strengthening dollar — supported by the Fed's hawkish stance versus more dovish EM central banks — added further headwinds for the asset class.",
          "topHoldings": "INSL CASH ~1% — top 1 = ~1%."
        },
        {
          "tier": "screener",
          "ticker": "LQDA",
          "name": "iShares USD Corporate Bond",
          "category": "USD corporate bonds",
          "pct": -1.82,
          "holds": "iShares USD Corporate Bond — USD corporate bonds fund on the Lightyear list. ~3122 holdings.",
          "vsCategory": "Outperformed the USD corporate bonds category average (-1.8%) by ~0pts over 1M.",
          "returnRisk": "0.2 return/risk (1Y, EUR); 1Y volatility 8%.",
          "week52": "38% of 52-week range.",
          "aumFlow": "AUM EUR 3,953M — flow baseline being established (first tracked period).",
          "aumEurM": 3953
        },
        {
          "tier": "screener",
          "ticker": "SPX4",
          "name": "SPDR S&P 400 US Mid Cap",
          "category": "US mid cap stocks",
          "pct": -1.79,
          "holds": "SPDR S&P 400 US Mid Cap — US mid cap stocks fund on the Lightyear list. ~400 holdings.",
          "vsCategory": "Outperformed the US mid cap stocks category average (-1.8%) by ~0pts over 1M.",
          "returnRisk": "0.8 return/risk (1Y, EUR); 1Y volatility 22%.",
          "week52": "84% of 52-week range.",
          "aumFlow": "AUM EUR 5,555M — flow baseline being established (first tracked period).",
          "aumEurM": 5555
        },
        {
          "tier": "screener",
          "ticker": "SEGA",
          "name": "iShares Core Euro Government Bond",
          "category": "Eurozone government bonds",
          "pct": -0.83,
          "holds": "iShares Core Euro Government Bond — Eurozone government bonds fund on the Lightyear list. ~552 holdings.",
          "vsCategory": "Underperformed the Eurozone government bonds category average (-0.6%) by ~0pts over 1M.",
          "returnRisk": "-0.1 return/risk (1Y, EUR); 1Y volatility 4%.",
          "week52": "16% of 52-week range.",
          "aumFlow": "AUM EUR 5,372M (+0.3% 1M). Implied flow +1.2pp vs return — net inflows beyond price effect.",
          "aumEurM": 5372
        }
      ]
    },
    "6m": {
      "best": [
        {
          "tier": "researched",
          "ticker": "CYSE",
          "name": "WisdomTree Cybersecurity",
          "category": "Cybersecurity stocks",
          "pct": 76.88,
          "holds": "WisdomTree Cybersecurity — Cybersecurity stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Cybersecurity stocks category average (+76.9%) by ~0pts over 6M.",
          "returnRisk": "1.0 return/risk (1Y, EUR); 1Y volatility 36%.",
          "week52": "92% of 52-week range.",
          "aumFlow": "AUM EUR 390M (+9.2% 1M). Implied flow -5.4pp vs return — money is leaving despite the price move.",
          "aumEurM": 390,
          "whyItMoved": "AI-driven cyber threats surged 89% YoY per CrowdStrike's 2026 Threat Hunting Report, pushing cybersecurity from discretionary IT spend to utility-like infrastructure. Q2 earnings beats from Okta (+22%) and CrowdStrike (+13%) in late August confirmed the demand surge, with top holdings Palo Alto Networks and Fortinet also rallying on cloud-vulnerability tailwinds.",
          "topHoldings": "CrowdStrike Holdings ~7%, Datadog ~7%, Palo Alto Networks ~6%, Fortinet Inc ~6%, Okta ~6% — top 10 = ~57%."
        },
        {
          "tier": "researched",
          "ticker": "SMGB",
          "name": "VanEck Semiconductor",
          "category": "Semiconductors / US semiconductor stocks",
          "pct": 49.31,
          "holds": "VanEck Semiconductor — Semiconductors / US semiconductor stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Semiconductors / US semiconductor stocks category average (+49.3%) by ~0pts over 6M.",
          "returnRisk": "2.7 return/risk (1Y, EUR); 1Y volatility 42%.",
          "week52": "71% of 52-week range.",
          "aumFlow": "AUM EUR 7,311M (+11.1% 1M). Implied flow +6.9pp vs return — net inflows beyond price effect.",
          "aumEurM": 7311,
          "whyItMoved": "Explosive AI chip demand drove the concentrated 25-stock portfolio higher. NVIDIA reported Q2 revenue of $96.2B (+106% YoY) with Blackwell GPU shipments accelerating, while AMD surged on a Raymond James Strong Buy upgrade citing 64% projected EPS growth. Hyperscaler capex guidance exceeding $700B for 2026 underpinned the entire supply chain.",
          "topHoldings": "AMD ~11%, Broadcom Inc. ~11%, NVIDIA Corp. ~11%, Taiwan Semiconductor Manufacturing Co., Ltd. ~10%, ASML Holding NV ~10% — top 10 = ~83%."
        },
        {
          "tier": "screener",
          "ticker": "AIFS",
          "name": "iShares AI Infrastructure",
          "category": "AI infrastructure stocks",
          "pct": 46.87,
          "holds": "iShares AI Infrastructure — AI infrastructure stocks fund on the Lightyear list. ~53 holdings.",
          "vsCategory": "Outperformed the AI infrastructure stocks category average (+46.9%) by ~0pts over 6M.",
          "returnRisk": "3.3 return/risk (1Y, EUR); 1Y volatility 26%.",
          "week52": "88% of 52-week range.",
          "aumFlow": "AUM EUR 1,080M (+26.5% 1M). Implied flow +16.6pp vs return — net inflows beyond price effect.",
          "aumEurM": 1080
        },
        {
          "tier": "screener",
          "ticker": "SEC0",
          "name": "iShares MSCI Global Semiconductors",
          "category": "Global semiconductor stocks",
          "pct": 46.61,
          "holds": "iShares MSCI Global Semiconductors — Global semiconductor stocks fund on the Lightyear list. ~259 holdings.",
          "vsCategory": "Outperformed the Global semiconductor stocks category average (+46.6%) by ~0pts over 6M.",
          "returnRisk": "3.5 return/risk (1Y, EUR); 1Y volatility 37%.",
          "week52": "69% of 52-week range.",
          "aumFlow": "AUM EUR 5,080M (+17.5% 1M). Implied flow +11.6pp vs return — net inflows beyond price effect.",
          "aumEurM": 5080
        },
        {
          "tier": "screener",
          "ticker": "ITWN",
          "name": "iShares MSCI Taiwan",
          "category": "Taiwan large and mid-cap stocks",
          "pct": 44.47,
          "holds": "iShares MSCI Taiwan — Taiwan large and mid-cap stocks fund on the Lightyear list. ~77 holdings.",
          "vsCategory": "Outperformed the Taiwan large and mid-cap stocks category average (+44.5%) by ~0pts over 6M.",
          "returnRisk": "3.2 return/risk (1Y, EUR); 1Y volatility 30%.",
          "week52": "93% of 52-week range.",
          "aumFlow": "AUM EUR 1,362M (+14.8% 1M). Implied flow +1.4pp vs return — net inflows beyond price effect.",
          "aumEurM": 1362
        }
      ],
      "worst": [
        {
          "tier": "researched",
          "ticker": "IAUP",
          "name": "iShares Gold Producers",
          "category": "Gold mining stocks",
          "pct": -8.46,
          "holds": "iShares Gold Producers — Gold mining stocks fund on the Lightyear list. ~82 holdings.",
          "vsCategory": "Outperformed the Gold mining stocks category average (-8.5%) by ~0pts over 6M.",
          "returnRisk": "1.7 return/risk (1Y, EUR); 1Y volatility 41%.",
          "week52": "79% of 52-week range.",
          "aumFlow": "AUM EUR 4,220M (+45.8% 1M). Implied flow +11.5pp vs return — net inflows beyond price effect.",
          "aumEurM": 4220,
          "badges": [
            "reversal watch"
          ],
          "whyItMoved": "Over 6 months gold miners suffered a volatile round-trip: a Q2 selloff driven by rising real yields and profit-taking after the 2025 rally, followed by a sharp August rebound. The net result was negative despite gold itself holding near record levels, as miners' higher operating costs and rising energy inputs compressed margins during the mid-year pullback.",
          "topHoldings": "Newmont Corp. ~10%, Agnico Eagle Mines Ltd. ~10%, Barrick Mining Corp. ~9%, Wheaton Precious Metals Corp. ~7%, Franco-Nevada ~6% — top 10 = ~61%."
        },
        {
          "tier": "researched",
          "ticker": "DFEN",
          "name": "VanEck Defense",
          "category": "Defence stocks / Defense stocks",
          "pct": -7.79,
          "holds": "VanEck Defense — Defence stocks / Defense stocks fund on the Lightyear list. ~45 holdings.",
          "vsCategory": "Outperformed the Defence stocks / Defense stocks category average (-7.8%) by ~0pts over 6M.",
          "returnRisk": "0.4 return/risk (1Y, EUR); 1Y volatility 25%.",
          "week52": "38% of 52-week range.",
          "aumFlow": "AUM EUR 6,449M (+5.7% 1M). Implied flow +2.7pp vs return — net inflows beyond price effect.",
          "aumEurM": 6449,
          "whyItMoved": "European defence stocks entered a consolidation phase after the 2025 rearmament rally. Rheinmetall crashed ~47% after Germany scrapped the €12.8B F126 frigate program, dragging the STOXX Europe Targeted Defence index down ~14% over 6 months. Investors shifted to demanding earnings proof rather than buying the spending narrative.",
          "topHoldings": "RTX ~10%, Palantir Technologies, Inc. ~8%, Thales SA ~7%, Leonardo SpA ~7%, Elbit Systems ~6% — top 10 = ~60%."
        },
        {
          "tier": "screener",
          "ticker": "IIND",
          "name": "iShares MSCI India",
          "category": "Indian stocks",
          "pct": -4.01,
          "holds": "iShares MSCI India — Indian stocks fund on the Lightyear list. ~165 holdings.",
          "vsCategory": "Outperformed the Indian stocks category average (-4.0%) by ~0pts over 6M.",
          "returnRisk": "-0.3 return/risk (1Y, EUR); 1Y volatility 16%.",
          "week52": "41% of 52-week range.",
          "aumFlow": "AUM EUR 4,462M (-1.7% 1M). Implied flow -1.3pp vs return — money is leaving despite the price move.",
          "aumEurM": 4462
        },
        {
          "tier": "screener",
          "ticker": "EUDF",
          "name": "WisdomTree Europe Defence",
          "category": "European defence stocks / European defense stocks",
          "pct": -3.96,
          "holds": "WisdomTree Europe Defence — European defence stocks / European defense stocks fund on the Lightyear list. ~41 holdings.",
          "vsCategory": "Outperformed the European defence stocks / European defense stocks category average (-4.0%) by ~0pts over 6M.",
          "returnRisk": "0.4 return/risk (1Y, EUR); 1Y volatility 27%.",
          "week52": "66% of 52-week range.",
          "aumFlow": "AUM EUR 4,630M (+2.2% 1M). Flow roughly neutral — AUM change tracks the price move.",
          "aumEurM": 4630
        },
        {
          "tier": "screener",
          "ticker": "SEGA",
          "name": "iShares Core Euro Government Bond",
          "category": "Eurozone government bonds",
          "pct": -2.9,
          "holds": "iShares Core Euro Government Bond — Eurozone government bonds fund on the Lightyear list. ~552 holdings.",
          "vsCategory": "Underperformed the Eurozone government bonds category average (-2.7%) by ~0pts over 6M.",
          "returnRisk": "-0.1 return/risk (1Y, EUR); 1Y volatility 4%.",
          "week52": "16% of 52-week range.",
          "aumFlow": "AUM EUR 5,372M (+0.3% 1M). Implied flow +1.2pp vs return — net inflows beyond price effect.",
          "aumEurM": 5372
        }
      ]
    },
    "ytd": {
      "best": [
        {
          "tier": "researched",
          "ticker": "IKOR",
          "name": "iShares MSCI Korea",
          "category": "Korean stocks",
          "pct": 89.24,
          "holds": "iShares MSCI Korea — Korean stocks fund on the Lightyear list. ~77 holdings.",
          "vsCategory": "Outperformed the Korean stocks category average (+89.2%) by ~0pts over YTD.",
          "returnRisk": "2.8 return/risk (1Y, EUR); 1Y volatility 57%.",
          "week52": "78% of 52-week range.",
          "aumFlow": "AUM EUR 1,024M (+23.8% 1M). Implied flow +4.3pp vs return — net inflows beyond price effect.",
          "aumEurM": 1024,
          "whyItMoved": "Samsung (+114% YTD) and SK Hynix (+143% YTD) drove the KOSPI to record levels on insatiable AI memory demand. Samsung began mass production of HBM4 chips for Nvidia's next-gen accelerators, while NAND supply tightness extended into 2027. Foreign investors reversed outflows, net buying ~$2B in a single week.",
          "topHoldings": "Samsung Electronics Co., Ltd. ~26%, SK hynix, Inc. ~14%, SK Square Co. Ltd. ~4%, Samsung Electronics Co., Ltd. ~3%, KB Financial Group, Inc. ~3% — top 10 = ~61%."
        },
        {
          "tier": "researched",
          "ticker": "SEC0",
          "name": "iShares MSCI Global Semiconductors",
          "category": "Global semiconductor stocks",
          "pct": 78.54,
          "holds": "iShares MSCI Global Semiconductors — Global semiconductor stocks fund on the Lightyear list. ~259 holdings.",
          "vsCategory": "Outperformed the Global semiconductor stocks category average (+78.5%) by ~0pts over YTD.",
          "returnRisk": "3.5 return/risk (1Y, EUR); 1Y volatility 37%.",
          "week52": "69% of 52-week range.",
          "aumFlow": "AUM EUR 5,080M (+17.5% 1M). Implied flow +11.6pp vs return — net inflows beyond price effect.",
          "aumEurM": 5080,
          "whyItMoved": "The broad 259-holding portfolio captured the full AI semiconductor cycle YTD: NVIDIA's Q2 revenue hit $96.2B (+106% YoY), Micron and AMD rallied on AI memory and accelerator demand, and TSMC benefited from insatiable foundry orders. Hyperscaler capex guidance exceeding $700B for 2026 signalled sustained demand across the supply chain.",
          "topHoldings": "Micron Technology ~9%, AMD ~9%, Taiwan Semiconductor Manufacturing Co., Ltd. ~7%, Broadcom Inc. ~7%, NVIDIA Corp. ~7% — top 10 = ~62%."
        },
        {
          "tier": "screener",
          "ticker": "SMGB",
          "name": "VanEck Semiconductor",
          "category": "Semiconductors / US semiconductor stocks",
          "pct": 72.62,
          "holds": "VanEck Semiconductor — Semiconductors / US semiconductor stocks fund on the Lightyear list. ~25 holdings.",
          "vsCategory": "Outperformed the Semiconductors / US semiconductor stocks category average (+72.6%) by ~0pts over YTD.",
          "returnRisk": "2.7 return/risk (1Y, EUR); 1Y volatility 42%.",
          "week52": "71% of 52-week range.",
          "aumFlow": "AUM EUR 7,311M (+11.1% 1M). Implied flow +6.9pp vs return — net inflows beyond price effect.",
          "aumEurM": 7311
        },
        {
          "tier": "screener",
          "ticker": "ITWN",
          "name": "iShares MSCI Taiwan",
          "category": "Taiwan large and mid-cap stocks",
          "pct": 72.52,
          "holds": "iShares MSCI Taiwan — Taiwan large and mid-cap stocks fund on the Lightyear list. ~77 holdings.",
          "vsCategory": "Outperformed the Taiwan large and mid-cap stocks category average (+72.5%) by ~0pts over YTD.",
          "returnRisk": "3.2 return/risk (1Y, EUR); 1Y volatility 30%.",
          "week52": "93% of 52-week range.",
          "aumFlow": "AUM EUR 1,362M (+14.8% 1M). Implied flow +1.4pp vs return — net inflows beyond price effect.",
          "aumEurM": 1362
        },
        {
          "tier": "screener",
          "ticker": "AIFS",
          "name": "iShares AI Infrastructure",
          "category": "AI infrastructure stocks",
          "pct": 55.41,
          "holds": "iShares AI Infrastructure — AI infrastructure stocks fund on the Lightyear list. ~53 holdings.",
          "vsCategory": "Outperformed the AI infrastructure stocks category average (+55.4%) by ~0pts over YTD.",
          "returnRisk": "3.3 return/risk (1Y, EUR); 1Y volatility 26%.",
          "week52": "88% of 52-week range.",
          "aumFlow": "AUM EUR 1,080M (+26.5% 1M). Implied flow +16.6pp vs return — net inflows beyond price effect.",
          "aumEurM": 1080
        }
      ],
      "worst": [
        {
          "tier": "researched",
          "ticker": "IIND",
          "name": "iShares MSCI India",
          "category": "Indian stocks",
          "pct": -8.04,
          "holds": "iShares MSCI India — Indian stocks fund on the Lightyear list. ~165 holdings.",
          "vsCategory": "Outperformed the Indian stocks category average (-8.0%) by ~0pts over YTD.",
          "returnRisk": "-0.3 return/risk (1Y, EUR); 1Y volatility 16%.",
          "week52": "41% of 52-week range.",
          "aumFlow": "AUM EUR 4,462M (-1.7% 1M). Implied flow -1.3pp vs return — money is leaving despite the price move.",
          "aumEurM": 4462,
          "whyItMoved": "Foreign investors rotated out of India into tech-heavy EM markets like Korea and Taiwan, with heavy FPI selling in financials (~30% of the portfolio). Rising crude oil prices from Strait of Hormuz tensions hit India as a major net importer, stoking inflation fears. MSCI India fell 8.5% YTD while MSCI EM rose 26%, making India the worst-performing major EM.",
          "topHoldings": "HDFC Bank Ltd. ~6%, Reliance Industries Ltd. ~6%, ICICI Bank Ltd. ~6%, Bharti Airtel Ltd. ~4%, Infosys Ltd. ~3% — top 10 = ~35%."
        },
        {
          "tier": "researched",
          "ticker": "SEGA",
          "name": "iShares Core Euro Government Bond",
          "category": "Eurozone government bonds",
          "pct": -0.81,
          "holds": "iShares Core Euro Government Bond — Eurozone government bonds fund on the Lightyear list. ~552 holdings.",
          "vsCategory": "Underperformed the Eurozone government bonds category average (-0.7%) by ~0pts over YTD.",
          "returnRisk": "-0.1 return/risk (1Y, EUR); 1Y volatility 4%.",
          "week52": "16% of 52-week range.",
          "aumFlow": "AUM EUR 5,372M (+0.3% 1M). Implied flow +1.2pp vs return — net inflows beyond price effect.",
          "aumEurM": 5372,
          "whyItMoved": "Record eurozone sovereign bond supply — gross issuance near €1.4T — met shrinking ECB demand as quantitative tightening stabilised at ~€350B/year. Yields rose to attract foreign buyers, pushing bond prices lower. France's fiscal weakness (5.5% deficit) and political instability added spread pressure across the bloc.",
          "topHoldings": "OAT0.5025MAY29 ~1% — top 1 = ~1%."
        },
        {
          "tier": "screener",
          "ticker": "OM3F",
          "name": "iShares EUR Corporate Bond ESG",
          "category": "ESG Euro corporate bonds",
          "pct": 0.21,
          "holds": "iShares EUR Corporate Bond ESG — ESG Euro corporate bonds fund on the Lightyear list. ~3216 holdings.",
          "vsCategory": "Underperformed the ESG Euro corporate bonds category average (+0.5%) by ~0pts over YTD.",
          "returnRisk": "0.2 return/risk (1Y, EUR); 1Y volatility 3%.",
          "week52": "61% of 52-week range.",
          "aumFlow": "AUM EUR 4,048M (+124.3% 1M). Implied flow +124.7pp vs return — net inflows beyond price effect.",
          "aumEurM": 4048
        },
        {
          "tier": "screener",
          "ticker": "IEAC",
          "name": "iShares Core Euro Corporate Bond",
          "category": "Eurozone corporate bonds",
          "pct": 0.18,
          "holds": "iShares Core Euro Corporate Bond — Eurozone corporate bonds fund on the Lightyear list. ~4149 holdings.",
          "vsCategory": "Underperformed the Eurozone corporate bonds category average (+0.2%) by ~0pts over YTD.",
          "returnRisk": "0.3 return/risk (1Y, EUR); 1Y volatility 3%.",
          "week52": "58% of 52-week range.",
          "aumFlow": "AUM EUR 8,722M — flow baseline being established (first tracked period).",
          "aumEurM": 8722
        },
        {
          "tier": "screener",
          "ticker": "VECP",
          "name": "Vanguard EUR Corporate Bond",
          "category": "Eurozone corporate bonds",
          "pct": 0.24,
          "holds": "Vanguard EUR Corporate Bond — Eurozone corporate bonds fund on the Lightyear list. ~3580 holdings.",
          "vsCategory": "Outperformed the Eurozone corporate bonds category average (+0.2%) by ~0pts over YTD.",
          "returnRisk": "0.3 return/risk (1Y, EUR); 1Y volatility 3%.",
          "week52": "60% of 52-week range.",
          "aumFlow": "AUM EUR 3,326M (+2.0% 1M). Implied flow +2.3pp vs return — net inflows beyond price effect.",
          "aumEurM": 3326
        }
      ]
    }
  },
  "portfolio": [
    {
      "ticker": "SEC0",
      "name": "iShares MSCI Global Semiconductors UCITS ETF USD (Acc)",
      "pct1m": 5.96,
      "pct6m": 46.61,
      "pctYtd": 78.54,
      "aumEurM": 5080,
      "holds": "The iShares MSCI Global Semiconductors UCITS ETF USD (Acc) seeks to track the MSCI ACWI IMI Semiconductors & Semiconductor Equipment ESG Screened Select Capped index. The MSCI ACWI IMI Semiconductors & Semiconductor Equipment ESG Screened Select Capped index tracks large, mid and small cap companies across 23 Developed Markets and 24 Emerging Markets that are active in the semiconductor industry. The stocks included are filtered according to ESG criteria (environmental, social and corporate governance).",
      "whyItMoved": "AI infrastructure capex exceeding $700B from hyperscalers powered the broad semiconductor rally. NVIDIA's Q2 revenue hit $96.2B (+106% YoY), Micron rallied on AI memory demand, and TSMC benefited from record foundry orders. The 1M gain of +6% reflects steady momentum into the NVIDIA earnings catalyst in late August.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "69% of 52-week range.",
      "aumFlow": "AUM EUR 5,080M (+17.5% 1M). Implied flow +11.6pp vs return — net inflows beyond price effect.",
      "topHoldings": "Micron Technology ~9%, AMD ~9%, Taiwan Semiconductor Manufacturing Co., Ltd. ~7%, Broadcom Inc. ~7%, NVIDIA Corp. ~7% — top 10 = ~62%."
    },
    {
      "ticker": "AIFS",
      "name": "iShares AI Infrastructure UCITS ETF USD (Acc)",
      "pct1m": 9.82,
      "pct6m": 46.87,
      "pctYtd": 55.41,
      "aumEurM": 1080,
      "holds": "The iShares AI Infrastructure UCITS ETF USD (Acc) seeks to track the STOXX Global AI Infrastructure index. The STOXX Global AI Infrastructure index tracks the performance of companies worldwide that are engaged in the field of AI infrastructure. The stocks included are filtered according to ESG criteria (environmental, social and corporate governance).",
      "whyItMoved": "Hyperscaler capex guidance exceeding $700B for 2026 drove sustained demand for AI infrastructure stocks. The fund's diversified mix across chips (Broadcom, AMD), cybersecurity (Palo Alto Networks), and platform (Microsoft, Apple) captured multiple AI tailwinds. The +9.8% monthly gain was amplified by strong inflows (+16.6pp above return), reflecting growing investor conviction in the AI buildout.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "88% of 52-week range.",
      "aumFlow": "AUM EUR 1,080M (+26.5% 1M). Implied flow +16.6pp vs return — net inflows beyond price effect.",
      "topHoldings": "Microsoft Corp ~5%, Apple ~5%, Palo Alto Networks ~5%, Broadcom Inc. ~4%, AMD ~4% — top 10 = ~43%."
    },
    {
      "ticker": "XAIX",
      "name": "Xtrackers Artificial Intelligence & Big Data UCITS ETF 1C",
      "pct1m": 9.15,
      "pct6m": 37.1,
      "pctYtd": 35.54,
      "aumEurM": 7633,
      "holds": "The Xtrackers Artificial Intelligence & Big Data UCITS ETF 1C seeks to track the Nasdaq Global Artificial Intelligence and Big Data index. The Nasdaq Global Artificial Intelligence and Big Data index tracks international companies of the sectors artificial intelligence, big data and cyber security. The stocks included are filtered according to ESG criteria (environmental, social and corporate governance).",
      "whyItMoved": "The broader AI/big data theme rallied on enterprise AI adoption accelerating across sectors. Top holdings Apple, Microsoft, Meta, and NVIDIA all benefited from the AI infrastructure spending cycle. The fund posted +27.8% last quarter alone, though its more diversified 166-holding portfolio (including cybersecurity and big data names) lagged the concentrated semiconductor plays YTD.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "87% of 52-week range.",
      "aumFlow": "AUM EUR 7,633M (+7.0% 1M). Implied flow -2.1pp vs return — money is leaving despite the price move.",
      "topHoldings": "Apple ~6%, Microsoft Corp ~5%, Meta Platforms ~5%, Walmart, Inc. ~5%, NVIDIA Corp. ~5% — top 10 = ~46%."
    },
    {
      "ticker": "IQQH",
      "name": "iShares Global Clean Energy Transition UCITS ETF USD (Dist)",
      "pct1m": 0.34,
      "pct6m": -1.62,
      "pctYtd": 8.77,
      "aumEurM": 2687,
      "holds": "The iShares Global Clean Energy Transition UCITS ETF USD (Dist) seeks to track the S&P Global Clean Energy Transition index. The S&P Global Clean Energy Transition index tracks the largest and most liquid stocks worldwide which are involved in clean energy business.",
      "whyItMoved": "Clean energy ETFs gained ~25%+ in 2026 on AI data centre demand locking solar into power purchase agreements at $39/MWh. However, this fund's 'transition' mandate — broader than pure renewables — diluted the upside, with mixed performance from holdings like China Yangtze Power. The flat 1M (+0.3%) and negative 6M (-1.6%) reflect mid-year volatility around rising bond yields.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "38% of 52-week range.",
      "aumFlow": "AUM EUR 2,687M (+2.4% 1M). Implied flow +2.0pp vs return — net inflows beyond price effect.",
      "topHoldings": "China Yangtze Power Co., Ltd. ~8%, First Solar ~8%, Nextpower ~8%, Bloom Energy ~7%, Enphase Energy ~5% — top 10 = ~50%."
    },
    {
      "ticker": "EQQQ",
      "name": "Invesco EQQQ Nasdaq-100 UCITS ETF",
      "pct1m": 4.9,
      "pct6m": 21.28,
      "pctYtd": 19.36,
      "aumEurM": 11645,
      "holds": "The Invesco EQQQ Nasdaq-100 UCITS ETF seeks to track the Nasdaq 100® index. The Nasdaq 100® index tracks a selection of 100 stocks chosen from among non-financial stocks listed on the NASDAQ stock exchange.",
      "whyItMoved": "The Nasdaq-100 gained ~16.6% YTD, driven by AI mega-caps. NVIDIA's Q2 earnings beat (+$442B market cap in one day after reporting $96.2B revenue) and Salesforce results reinforced the AI trade. Apple, Microsoft, and Micron in the top holdings all contributed to steady gains, with the 1M +4.9% reflecting broad late-August tech momentum.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "86% of 52-week range.",
      "aumFlow": "AUM EUR 11,645M (+7.8% 1M). Implied flow +2.9pp vs return — net inflows beyond price effect.",
      "topHoldings": "Apple ~8%, NVIDIA Corp. ~8%, Microsoft Corp ~5%, Micron Technology ~5%, Amazon.com, Inc. ~4% — top 10 = ~46%."
    },
    {
      "ticker": "IQQK",
      "name": "iShares MSCI Korea UCITS ETF (Dist)",
      "pct1m": 19.54,
      "pct6m": 22.72,
      "pctYtd": 89.24,
      "aumEurM": 1024,
      "holds": "The iShares MSCI Korea UCITS ETF (Dist) seeks to track the MSCI Korea 20/35 index. The MSCI Korea 20/35 index tracks large and mid cap Korean stocks. The weight of the largest constituent is constrained to 35% and the weights of all other constituents are constrained to a maximum of 20%.",
      "whyItMoved": "Samsung (+114% YTD) and SK Hynix (+143% YTD) — together ~40% of the fund — drove the extraordinary return on AI memory chip demand and HBM4 mass production for Nvidia. The 1M +19.5% came after a sharp July correction (-22% KOSPI drawdown) reversed on foreign buying and share buyback hopes. Supply tightness in NAND and HBM may extend into 2027.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "78% of 52-week range.",
      "aumFlow": "AUM EUR 1,024M (+23.8% 1M). Implied flow +4.3pp vs return — net inflows beyond price effect.",
      "topHoldings": "Samsung Electronics Co., Ltd. ~26%, SK hynix, Inc. ~14%, SK Square Co. Ltd. ~4%, Samsung Electronics Co., Ltd. ~3%, KB Financial Group, Inc. ~3% — top 10 = ~61%."
    },
    {
      "ticker": "WTE",
      "name": "WisdomTree Physical Palladium",
      "pct1m": 12.34,
      "pct6m": -17.77,
      "pctYtd": -6.41,
      "holds": "The palladium spot price is the price of palladium in US Dollar.",
      "whyItMoved": "Palladium is moving into surplus in 2026 for the first time in 14 years — UBS cut its target to $1,400/oz — as EV adoption reduces autocatalyst demand and Chinese scrap supply rises. The 6M decline of -17.8% reflects this structural shift. The 1M rebound (+12.3%) came with the broader precious metals rally in August on softer US labour data and easing Iran tensions.",
      "vsCategory": "Portfolio holding — see performers tables for category context.",
      "returnRisk": "See fund page metrics.",
      "week52": "37% of 52-week range.",
      "aumFlow": "AUM not published."
    }
  ]
};
